const COPY = {
  en: {
    base: "",
    locale: "en-GB",
    schema: {
      headline: "How EU Debt Map calculates live government debt estimates",
      datasetName: "Eurostat quarterly government debt used by EU Debt Map",
      datasetDescription: "Validated EU-27 quarterly general government gross debt observations used as official anchors for EU Debt Map.",
      spatialCoverage: "European Union",
      home: "Home",
      page: "Methodology",
    },
    previewLabel: "Methodology design study · isolated preview",
    currentPage: "View current page",
    eyebrow: "Data provenance · Calculation · Limitations",
    title: "From Eurostat data to live EU debt estimates.",
    lede:
      "EU Debt Map separates published facts from modelled movement. This page shows every important step—from the original quarterly observation to the number moving on screen.",
    heroAction: "Follow the data",
    heroNote: "Method version 2.0 · reviewed 30 August 2026",
    sourcePanel: "The data lineage",
    sourceSteps: [
      ["01", "Eurostat", "Official quarterly observations"],
      ["02", "Validation", "Coverage, dates and values checked"],
      ["03", "Snapshot", "Last-known-good data stored locally"],
      ["04", "Model", "Quarterly movement expressed per second"],
      ["05", "Display", "Official and estimated values labelled separately"],
    ],
    facts: {
      source: "Source",
      coverage: "Coverage",
      coverageNote: (coverage) => `${coverage}/27 in the shared period`,
      reference: "Latest reference",
      referenceNote: "Official quarter-end stock",
      fetched: "Last fetched",
      fetchedNote: "Stored, validated snapshot",
    },
    navLabel: "Methodology",
    nav: ["Overview", "Definition", "Pipeline", "Calculation", "Safeguards", "Limits", "Sources"],
    overview: {
      eyebrow: "01 — The short answer",
      title: "One official number. One clearly labelled model.",
      intro:
        "The debt stock and debt-to-GDP ratio come from Eurostat. The live counter does not. EU Debt Map extends the change between the two latest official quarters at a constant pace so the scale and direction remain visible between releases.",
      officialLabel: "Official observation",
      officialTitle: "Published by Eurostat",
      officialText:
        "A dated quarterly stock of consolidated general government gross debt, plus Eurostat’s official percentage-of-GDP series.",
      modelLabel: "Modelled estimate",
      modelTitle: "Calculated by EU Debt Map",
      modelText:
        "A linear continuation of the latest observed quarterly movement. It is an educational display—not an official statistic or forecast.",
      ruleLabel: "The rule that governs the whole site",
      rule: "If a number moves every second, it is modelled. If it is official, it carries a Eurostat reference period.",
    },
    definition: {
      eyebrow: "02 — What is being measured",
      title: "The debt measure is narrower—and more precise—than ‘everything a government owes’.",
      intro:
        "EU Debt Map uses Maastricht debt: consolidated gross debt at nominal value for the general government sector at the end of each quarter.",
      includedTitle: "Included in Maastricht debt",
      included: [
        ["AF.2", "Currency and deposits"],
        ["AF.3", "Debt securities"],
        ["AF.4", "Loans"],
      ],
      coverageTitle: "General government means",
      coverage: ["Central government", "State government where applicable", "Local government", "Social security funds"],
      excludedTitle: "Do not read it as",
      excluded: [
        "Net debt after subtracting government assets",
        "A complete measure of future pensions or other contingent obligations",
        "The budget deficit, which is a flow rather than a stock",
        "A real-time government accounting balance",
      ],
      sourceLink: "Read Eurostat’s complete reference metadata",
    },
    pipeline: {
      eyebrow: "03 — Source to screen",
      title: "A reproducible chain, with no live API dependency during normal builds.",
      intro:
        "The source is remote; the production experience is deliberately stable. New observations are fetched in a controlled update, validated, and written to local snapshots before a deployment can use them.",
      steps: [
        ["Fetch", "Request gov_10q_ggdebt for all EU-27 countries in MIO_EUR and PC_GDP."],
        ["Normalize", "Map Eurostat’s EL code to GR and convert million-euro values into euros."],
        ["Validate", "Reject missing countries, invalid periods and values that disagree with the stored history."],
        ["Preserve", "If a country is absent from a valid update, retain its last-known-good official observation."],
        ["Publish", "Advance the shared EU-27 period only after all 27 countries are available for that quarter."],
      ],
      statusLabel: "Current validated snapshot",
      dataGenerated: "Debt data fetched",
      ratioGenerated: "Ratio data fetched",
      coverage: "Shared-period coverage",
      period: "Reference period",
    },
    calculation: {
      eyebrow: "04 — The model",
      title: "The counter converts one quarterly change into a constant per-second pace.",
      intro:
        "No growth, interest-rate or policy assumption is added. The model only spreads the most recent observed change across time and continues that pace after the latest quarter-end.",
      rateLabel: "Modelled rate",
      rateFormula: "(latest official debt − previous official debt) ÷ seconds between both dates",
      estimateLabel: "Estimate after the latest reference date",
      estimateFormula: "latest official debt + rate × seconds elapsed since the latest date",
      exampleEyebrow: "Worked example · current German snapshot",
      previous: "Previous official debt",
      latest: "Latest official debt",
      movement: "Quarterly movement",
      elapsed: "Time between anchors",
      days: (days) => `${days} days`,
      pace: "Modelled pace",
      exampleNote:
        "Rounded display values may not reproduce the exact rate. The calculation uses the full stored euro amounts and UTC quarter-end timestamps.",
      ratioTitle: "How the live debt-to-GDP estimate works",
      ratioText:
        "Eurostat’s published ratio is the official starting point. The optional live view scales that ratio by the change in the modelled debt total while holding the implied GDP denominator constant.",
      ratioFormula: "official ratio × (modelled debt now ÷ official debt at the reference date)",
      ratioWarning: "That makes it an estimate of the ratio—not a live GDP measurement and not a forecast.",
    },
    safeguards: {
      eyebrow: "05 — Guardrails",
      title: "The model is allowed to stop before it is allowed to mislead.",
      intro:
        "Quarterly data can be delayed, revised or incomplete. Conservative rules keep an unusual source response from becoming a runaway counter.",
      cards: [
        ["€50,000/s hard cap", "Any calculated country pace is constrained between −€50,000 and +€50,000 per second."],
        ["Stale-country freeze", "A country more than one shared quarter behind is still shown at its last official value, but its ticker is frozen."],
        ["Missing-history fallback", "Without two usable observations, movement defaults to zero until a valid comparison exists."],
        ["Period consistency", "Quarter labels are converted to UTC quarter-end dates before elapsed time is calculated."],
        ["Shared EU period", "The EU-27 history advances only with complete 27-country coverage, preventing false total comparisons."],
        ["No silent substitution", "Official debt and official debt-to-GDP remain separate series; a missing ratio is not invented from another source."],
      ],
    },
    limitations: {
      eyebrow: "06 — Read the estimate responsibly",
      title: "Precision on screen is not precision in the underlying economy.",
      intro:
        "The counter is useful for scale, direction and comparison. It cannot reveal what happened on a particular day or predict the next official observation.",
      items: [
        ["Debt does not move smoothly", "Governments issue, redeem and revalue debt in discrete transactions. A linear ticker is a visual model."],
        ["Euro values can include exchange-rate movement", "For non-euro countries, Eurostat converts debt using the exchange rate at the last working day of the quarter."],
        ["Official histories can be revised", "National authorities and Eurostat may revise earlier quarters after new information, corrections or methodological changes."],
        ["Gross debt is not fiscal health", "Assets, interest costs, maturity, deficits, growth and currency structure also matter."],
        ["Country releases need not arrive together", "A country can temporarily retain an older official quarter while newer shared data are incomplete."],
        ["The model is not advice", "EU Debt Map is an independent educational visualization, not official reporting, forecasting or investment guidance."],
      ],
    },
    updates: {
      eyebrow: "07 — Freshness and corrections",
      title: "Every displayed update should be traceable to a source date and a method version.",
      intro:
        "Eurostat normally publishes quarterly government debt after national reporting and validation. Revisions can also arrive between regular releases.",
      cards: [
        ["Official cadence", "Quarterly; Member States transmit data within roughly three months after quarter-end."],
        ["Site refresh", "A controlled data update, validation and deployment—not an automatic browser-side API request."],
        ["Corrections", "A corrected official observation replaces the stored value after it passes the same validation checks."],
      ],
      changelogTitle: "Method record",
      changelog: [
        ["Version 2.0", "30 Aug 2026", "Adds live-ratio logic, stale-data freezes, exact guardrails, revisions and foreign-exchange limitations."],
        ["1.2", "Jul 2026", "Documents validated snapshots, official ratios and last-known-good country updates."],
      ],
    },
    sources: {
      eyebrow: "08 — Audit the method",
      title: "Original source, exact filters and a citation you can reuse.",
      intro:
        "The short explanation stays readable; the technical record remains one click away for researchers and developers.",
      sourceCards: [
        ["Primary dataset", "Eurostat · gov_10q_ggdebt", "Quarterly general government gross debt"],
        ["Debt unit", "MIO_EUR", "Converted to euros by multiplying by 1,000,000"],
        ["Official ratio unit", "PC_GDP", "Stored directly from Eurostat’s percentage-of-GDP observation"],
        ["Filters", "Q · S13 · GD · EU-27", "Quarterly · general government · gross debt"],
      ],
      detailsTitle: "Technical query and pseudocode",
      citationTitle: "Suggested citation",
      citation:
        "EU Debt Map (2026), ‘Methodology: Eurostat data and live government debt estimates’, based on Eurostat gov_10q_ggdebt. Accessed 30 August 2026.",
      copyHint: "Use the original Eurostat source alongside EU Debt Map when reusing the figures.",
      linkLabels: ["Official metadata", "Dataset", "JSON API"],
      primary: "Eurostat reference metadata",
      dataset: "Open the Eurostat dataset",
      api: "Open the source API",
      nextTitle: "Continue with the data",
      next: [
        ["Open the EU-27 map", "/"],
        ["Compare debt-to-GDP", "/debt-to-gdp"],
        ["Read the debt explainer", "/debt"],
        ["View the fiscal rules", "/stability-and-growth-pact"],
      ],
    },
  },
  nl: {
    base: "/nl",
    locale: "nl-NL",
    schema: {
      headline: "Hoe EU Debt Map live schattingen van de overheidsschuld berekent",
      datasetName: "Driemaandelijkse Eurostat-overheidsschuld gebruikt door EU Debt Map",
      datasetDescription: "Gevalideerde driemaandelijkse waarnemingen van de geconsolideerde bruto overheidsschuld van de EU-27 die EU Debt Map als officiële ankerpunten gebruikt.",
      spatialCoverage: "Europese Unie",
      home: "Home",
      page: "Methodologie",
    },
    previewLabel: "Ontwerpstudie methodologie · geïsoleerde preview",
    currentPage: "Bekijk huidige pagina",
    eyebrow: "Dataherkomst · Berekening · Beperkingen",
    title: "Van Eurostat-data naar live-schattingen van de EU-staatsschuld.",
    lede:
      "EU Debt Map houdt gepubliceerde feiten en gemodelleerde beweging uit elkaar. Deze pagina toont elke belangrijke stap: van de oorspronkelijke kwartaalwaarneming tot het getal dat op het scherm beweegt.",
    heroAction: "Volg de data",
    heroNote: "Methodeversie 2.0 · beoordeeld op 30 augustus 2026",
    sourcePanel: "De herkomst van de data",
    sourceSteps: [
      ["01", "Eurostat", "Officiële kwartaalwaarnemingen"],
      ["02", "Validatie", "Dekking, datums en waarden gecontroleerd"],
      ["03", "Momentopname", "Laatst bekende geldige data lokaal opgeslagen"],
      ["04", "Model", "Kwartaalbeweging omgerekend naar een tempo per seconde"],
      ["05", "Weergave", "Officiële waarden en schattingen afzonderlijk gelabeld"],
    ],
    facts: {
      source: "Bron",
      coverage: "Dekking",
      coverageNote: (coverage) => `${coverage}/27 in de gezamenlijke periode`,
      reference: "Nieuwste referentie",
      referenceNote: "Officiële schuldstand aan het einde van het kwartaal",
      fetched: "Laatst opgehaald",
      fetchedNote: "Opgeslagen, gevalideerde momentopname",
    },
    navLabel: "Methodologie",
    nav: ["Overzicht", "Definitie", "Dataketen", "Berekening", "Waarborgen", "Beperkingen", "Bronnen"],
    overview: {
      eyebrow: "01 — Het korte antwoord",
      title: "Eén officieel cijfer. Eén duidelijk gelabeld model.",
      intro:
        "De schuldstand en schuldquote komen van Eurostat. De live teller niet. EU Debt Map trekt de verandering tussen de twee nieuwste officiële kwartalen in een constant tempo door, zodat schaal en richting tussen publicaties zichtbaar blijven.",
      officialLabel: "Officiële waarneming",
      officialTitle: "Gepubliceerd door Eurostat",
      officialText:
        "Een gedateerde kwartaalstand van de geconsolideerde bruto schuld van de algemene overheid, plus de officiële Eurostat-reeks als percentage van het bbp.",
      modelLabel: "Gemodelleerde schatting",
      modelTitle: "Berekend door EU Debt Map",
      modelText:
        "Een lineaire voortzetting van de laatst waargenomen kwartaalbeweging. Het is een educatieve weergave, geen officiële statistiek of voorspelling.",
      ruleLabel: "De regel voor de hele website",
      rule: "Beweegt een getal iedere seconde, dan is het gemodelleerd. Is het officieel, dan staat er een Eurostat-referentieperiode bij.",
    },
    definition: {
      eyebrow: "02 — Wat wordt gemeten",
      title: "De schuldmaatstaf is nauwer — en preciezer — dan ‘alles wat een overheid verschuldigd is’.",
      intro:
        "EU Debt Map gebruikt de Maastrichtschuld: de geconsolideerde bruto schuld tegen nominale waarde van de algemene overheid aan het einde van ieder kwartaal.",
      includedTitle: "Opgenomen in de Maastrichtschuld",
      included: [
        ["AF.2", "Chartaal geld en deposito’s"],
        ["AF.3", "Schuldbewijzen"],
        ["AF.4", "Leningen"],
      ],
      coverageTitle: "Algemene overheid omvat",
      coverage: ["Centrale overheid", "Deelstaatoverheid waar van toepassing", "Lokale overheid", "Socialezekerheidsfondsen"],
      excludedTitle: "Lees het niet als",
      excluded: [
        "Nettoschuld na aftrek van overheidsbezittingen",
        "Een volledige maatstaf voor toekomstige pensioenen of andere voorwaardelijke verplichtingen",
        "Het begrotingstekort, dat een stroom is en geen voorraad",
        "Een realtime boekhoudkundig saldo van de overheid",
      ],
      sourceLink: "Lees de volledige referentiemetadata van Eurostat",
    },
    pipeline: {
      eyebrow: "03 — Van bron naar scherm",
      title: "Een reproduceerbare keten, zonder afhankelijkheid van een live-API tijdens normale builds.",
      intro:
        "De bron staat op afstand; de productieomgeving is bewust stabiel. Nieuwe waarnemingen worden gecontroleerd opgehaald, gevalideerd en naar lokale momentopnamen geschreven voordat een deployment ze kan gebruiken.",
      steps: [
        ["Ophalen", "Vraag gov_10q_ggdebt op voor alle EU-27-landen in MIO_EUR en PC_GDP."],
        ["Normaliseren", "Zet Eurostats landcode EL om naar GR en reken miljoenen euro’s om naar euro’s."],
        ["Valideren", "Weiger ontbrekende landen, ongeldige perioden en waarden die niet overeenkomen met de opgeslagen historie."],
        ["Behouden", "Ontbreekt een land in een geldige update, behoud dan de laatst bekende geldige officiële waarneming."],
        ["Publiceren", "Schuif de gezamenlijke EU-27-periode pas door als voor dat kwartaal alle 27 landen beschikbaar zijn."],
      ],
      statusLabel: "Huidige gevalideerde momentopname",
      dataGenerated: "Schulddata opgehaald",
      ratioGenerated: "Schuldquotedata opgehaald",
      coverage: "Dekking gezamenlijke periode",
      period: "Referentieperiode",
    },
    calculation: {
      eyebrow: "04 — Het model",
      title: "De teller zet één kwartaalverandering om in een constant tempo per seconde.",
      intro:
        "Er wordt geen aanname over groei, rente of beleid toegevoegd. Het model spreidt alleen de laatst waargenomen verandering over de tijd en zet dat tempo na het nieuwste kwartaaleinde voort.",
      rateLabel: "Gemodelleerd tempo",
      rateFormula: "(nieuwste officiële schuld − vorige officiële schuld) ÷ seconden tussen beide datums",
      estimateLabel: "Schatting na de nieuwste referentiedatum",
      estimateFormula: "nieuwste officiële schuld + tempo × verstreken seconden sinds de nieuwste datum",
      exampleEyebrow: "Rekenvoorbeeld · huidige Duitse momentopname",
      previous: "Vorige officiële schuld",
      latest: "Nieuwste officiële schuld",
      movement: "Kwartaalbeweging",
      elapsed: "Tijd tussen ankerpunten",
      days: (days) => `${days} dagen`,
      pace: "Gemodelleerd tempo",
      exampleNote:
        "Afgeronde weergavewaarden leveren mogelijk niet exact hetzelfde tempo op. De berekening gebruikt de volledige opgeslagen eurobedragen en UTC-tijdstippen aan het einde van het kwartaal.",
      ratioTitle: "Zo werkt de live-schatting van de schuldquote",
      ratioText:
        "De gepubliceerde Eurostat-ratio is het officiële uitgangspunt. De optionele live weergave schaalt die ratio met de verandering in de gemodelleerde schuldstand, terwijl de afgeleide bbp-noemer constant blijft.",
      ratioFormula: "officiële ratio × (gemodelleerde schuld nu ÷ officiële schuld op de referentiedatum)",
      ratioWarning: "Dit maakt het een schatting van de ratio, geen live meting van het bbp en geen voorspelling.",
    },
    safeguards: {
      eyebrow: "05 — Waarborgen",
      title: "Het model mag stoppen voordat het mag misleiden.",
      intro:
        "Kwartaaldata kan vertraagd, herzien of onvolledig zijn. Voorzichtige regels voorkomen dat een ongebruikelijke bronrespons een ontsporende teller veroorzaakt.",
      cards: [
        ["Harde limiet van €50.000/s", "Ieder berekend landtempo wordt begrensd tussen −€50.000 en +€50.000 per seconde."],
        ["Bevriezing bij verouderde data", "Een land dat meer dan één gezamenlijke kwartaalperiode achterloopt, blijft zichtbaar op de laatste officiële waarde, maar de teller wordt stilgezet."],
        ["Terugval bij ontbrekende historie", "Zonder twee bruikbare waarnemingen wordt de beweging nul totdat een geldige vergelijking beschikbaar is."],
        ["Consistente perioden", "Kwartaalcodes worden omgezet naar UTC-datums aan het einde van het kwartaal voordat de verstreken tijd wordt berekend."],
        ["Gezamenlijke EU-periode", "De EU-27-historie schuift alleen door bij volledige dekking van 27 landen, zodat misleidende totaalvergelijkingen worden voorkomen."],
        ["Geen stille vervanging", "Officiële schuld en officiële schuldquote blijven afzonderlijke reeksen; een ontbrekende ratio wordt niet uit een andere bron verzonnen."],
      ],
    },
    limitations: {
      eyebrow: "06 — Lees de schatting verantwoord",
      title: "Precisie op het scherm is geen precisie in de onderliggende economie.",
      intro:
        "De teller is nuttig voor schaal, richting en vergelijking. Hij kan niet laten zien wat op een specifieke dag gebeurde of de volgende officiële waarneming voorspellen.",
      items: [
        ["Schuld beweegt niet gelijkmatig", "Overheden geven schuld uit, lossen af en herwaarderen via afzonderlijke transacties. Een lineaire teller is een visueel model."],
        ["Eurowaarden kunnen wisselkoersbewegingen bevatten", "Voor landen buiten de eurozone rekent Eurostat schuld om tegen de wisselkoers van de laatste werkdag van het kwartaal."],
        ["Officiële historie kan worden herzien", "Nationale autoriteiten en Eurostat kunnen eerdere kwartalen herzien na nieuwe informatie, correcties of methodologische wijzigingen."],
        ["Brutoschuld is niet hetzelfde als budgettaire gezondheid", "Ook bezittingen, rentelasten, looptijd, tekorten, groei en valutasamenstelling zijn van belang."],
        ["Landpublicaties hoeven niet tegelijk te verschijnen", "Een land kan tijdelijk een ouder officieel kwartaal behouden terwijl nieuwere gezamenlijke data nog onvolledig is."],
        ["Het model is geen advies", "EU Debt Map is een onafhankelijke educatieve visualisatie, geen officiële rapportage, voorspelling of beleggingsadvies."],
      ],
    },
    updates: {
      eyebrow: "07 — Actualiteit en correcties",
      title: "Iedere getoonde update moet herleidbaar zijn tot een brondatum en methodeversie.",
      intro:
        "Eurostat publiceert de driemaandelijkse overheidsschuld doorgaans na nationale rapportage en validatie. Ook tussen reguliere publicaties kunnen herzieningen verschijnen.",
      cards: [
        ["Officieel ritme", "Driemaandelijks; lidstaten leveren de data doorgaans binnen ongeveer drie maanden na het kwartaaleinde aan."],
        ["Website-update", "Een gecontroleerde data-update, validatie en deployment, geen automatische API-aanvraag vanuit de browser."],
        ["Correcties", "Een gecorrigeerde officiële waarneming vervangt de opgeslagen waarde nadat deze dezelfde validatiecontroles doorstaat."],
      ],
      changelogTitle: "Methoderegister",
      changelog: [
        ["Versie 2.0", "30 aug. 2026", "Voegt logica voor de live schuldquote, bevriezing van verouderde data, exacte waarborgen, herzieningen en wisselkoersbeperkingen toe."],
        ["1.2", "jul. 2026", "Documenteert gevalideerde momentopnamen, officiële ratio’s en updates met de laatst bekende geldige landdata."],
      ],
    },
    sources: {
      eyebrow: "08 — Controleer de methode",
      title: "Oorspronkelijke bron, exacte filters en een herbruikbare bronvermelding.",
      intro:
        "De korte uitleg blijft leesbaar; het technische dossier blijft voor onderzoekers en ontwikkelaars één klik verwijderd.",
      sourceCards: [
        ["Primaire dataset", "Eurostat · gov_10q_ggdebt", "Driemaandelijkse bruto schuld van de algemene overheid"],
        ["Schuldeenheid", "MIO_EUR", "Omgezet naar euro’s door met 1.000.000 te vermenigvuldigen"],
        ["Officiële ratio-eenheid", "PC_GDP", "Rechtstreeks opgeslagen uit Eurostats waarneming als percentage van het bbp"],
        ["Filters", "Q · S13 · GD · EU-27", "Driemaandelijks · algemene overheid · bruto schuld"],
      ],
      detailsTitle: "Technische query en pseudocode",
      citationTitle: "Voorgestelde bronvermelding",
      citation:
        "EU Debt Map (2026), ‘Methodologie: Eurostat-data en live schattingen van de overheidsschuld’, gebaseerd op Eurostat gov_10q_ggdebt. Geraadpleegd op 30 augustus 2026.",
      copyHint: "Vermeld bij hergebruik van de cijfers naast EU Debt Map ook de oorspronkelijke Eurostat-bron.",
      linkLabels: ["Officiële metadata", "Dataset", "JSON-API"],
      primary: "Referentiemetadata van Eurostat",
      dataset: "Open de Eurostat-dataset",
      api: "Open de bron-API",
      nextTitle: "Ga verder met de data",
      next: [
        ["Open de EU-27-kaart", "/nl"],
        ["Vergelijk schuldquotes", "/nl/debt-to-gdp"],
        ["Lees de schulduitleg", "/nl/debt"],
        ["Bekijk de begrotingsregels", "/nl/stability-and-growth-pact"],
      ],
    },
  },
  de: {
    base: "/de",
    locale: "de-DE",
    schema: {
      headline: "Wie EU Debt Map Live-Schätzungen der Staatsverschuldung berechnet",
      datasetName: "Vierteljährliche Eurostat-Staatsschulden, die EU Debt Map verwendet",
      datasetDescription: "Validierte vierteljährliche Beobachtungen des konsolidierten Bruttoschuldenstands der EU-27, die EU Debt Map als offizielle Ankerpunkte verwendet.",
      spatialCoverage: "Europäische Union",
      home: "Startseite",
      page: "Methodik",
    },
    previewLabel: "Methodik-Entwurfsstudie · isolierte Vorschau",
    currentPage: "Aktuelle Seite ansehen",
    eyebrow: "Datenherkunft · Berechnung · Grenzen",
    title: "Von Eurostat-Daten zu Live-Schätzungen der EU-Staatsschulden.",
    lede:
      "EU Debt Map trennt veröffentlichte Fakten von modellierten Bewegungen. Diese Seite zeigt jeden wichtigen Schritt: von der ursprünglichen Quartalsbeobachtung bis zu der Zahl, die sich auf dem Bildschirm bewegt.",
    heroAction: "Dem Datenweg folgen",
    heroNote: "Methodenversion 2.0 · geprüft am 30. August 2026",
    sourcePanel: "Der Weg der Daten",
    sourceSteps: [
      ["01", "Eurostat", "Offizielle vierteljährliche Beobachtungen"],
      ["02", "Validierung", "Abdeckung, Daten und Werte geprüft"],
      ["03", "Datenstand", "Zuletzt bekannte gültige Daten lokal gespeichert"],
      ["04", "Modell", "Quartalsbewegung als Rate pro Sekunde ausgedrückt"],
      ["05", "Anzeige", "Offizielle Werte und Schätzungen getrennt gekennzeichnet"],
    ],
    facts: {
      source: "Quelle",
      coverage: "Abdeckung",
      coverageNote: (coverage) => `${coverage}/27 im gemeinsamen Zeitraum`,
      reference: "Neuester Referenzwert",
      referenceNote: "Offizieller Schuldenstand zum Quartalsende",
      fetched: "Zuletzt abgerufen",
      fetchedNote: "Gespeicherter, validierter Datenstand",
    },
    navLabel: "Methodik",
    nav: ["Überblick", "Definition", "Datenkette", "Berechnung", "Schutzregeln", "Grenzen", "Quellen"],
    overview: {
      eyebrow: "01 — Die kurze Antwort",
      title: "Eine offizielle Zahl. Ein klar gekennzeichnetes Modell.",
      intro:
        "Schuldenstand und Schuldenquote stammen von Eurostat. Der Live-Zähler nicht. EU Debt Map schreibt die Veränderung zwischen den beiden neuesten offiziellen Quartalen mit konstanter Rate fort, damit Größenordnung und Richtung zwischen den Veröffentlichungen sichtbar bleiben.",
      officialLabel: "Offizielle Beobachtung",
      officialTitle: "Von Eurostat veröffentlicht",
      officialText:
        "Ein datierter vierteljährlicher Stand der konsolidierten Bruttoschulden des Staates sowie Eurostats offizielle Reihe in Prozent des BIP.",
      modelLabel: "Modellierte Schätzung",
      modelTitle: "Von EU Debt Map berechnet",
      modelText:
        "Eine lineare Fortschreibung der zuletzt beobachteten Quartalsbewegung. Sie dient der Veranschaulichung und ist weder eine offizielle Statistik noch eine Prognose.",
      ruleLabel: "Die Regel für die gesamte Website",
      rule: "Bewegt sich eine Zahl jede Sekunde, ist sie modelliert. Ist sie offiziell, trägt sie einen Eurostat-Referenzzeitraum.",
    },
    definition: {
      eyebrow: "02 — Was gemessen wird",
      title: "Das Schuldenmaß ist enger — und genauer — als ‚alles, was ein Staat schuldet‘.",
      intro:
        "EU Debt Map verwendet den Maastricht-Schuldenstand: die konsolidierten Bruttoschulden zum Nominalwert des Sektors Staat am Ende jedes Quartals.",
      includedTitle: "Im Maastricht-Schuldenstand enthalten",
      included: [
        ["AF.2", "Bargeld und Einlagen"],
        ["AF.3", "Schuldverschreibungen"],
        ["AF.4", "Kredite"],
      ],
      coverageTitle: "Der Sektor Staat umfasst",
      coverage: ["Zentralstaat", "Länder, soweit vorhanden", "Gemeinden", "Sozialversicherung"],
      excludedTitle: "Nicht zu verstehen als",
      excluded: [
        "Nettoschulden nach Abzug staatlicher Vermögenswerte",
        "Vollständiges Maß künftiger Pensionen oder anderer Eventualverbindlichkeiten",
        "Haushaltsdefizit, das eine Stromgröße und kein Bestand ist",
        "Echtzeit-Buchhaltungssaldo des Staates",
      ],
      sourceLink: "Vollständige Eurostat-Referenzmetadaten lesen",
    },
    pipeline: {
      eyebrow: "03 — Von der Quelle zum Bildschirm",
      title: "Eine reproduzierbare Kette ohne Abhängigkeit von einer Live-API bei normalen Builds.",
      intro:
        "Die Quelle ist extern; die Produktionsumgebung bleibt bewusst stabil. Neue Beobachtungen werden kontrolliert abgerufen, validiert und in lokale Datenstände geschrieben, bevor eine Bereitstellung sie verwenden kann.",
      steps: [
        ["Abrufen", "gov_10q_ggdebt für alle EU-27-Länder in MIO_EUR und PC_GDP abfragen."],
        ["Normalisieren", "Eurostats Ländercode EL auf GR abbilden und Millionen Euro in Euro umrechnen."],
        ["Validieren", "Fehlende Länder, ungültige Zeiträume und Werte ablehnen, die der gespeicherten Historie widersprechen."],
        ["Bewahren", "Fehlt ein Land in einer gültigen Aktualisierung, bleibt seine zuletzt bekannte gültige offizielle Beobachtung erhalten."],
        ["Veröffentlichen", "Den gemeinsamen EU-27-Zeitraum erst fortschreiben, wenn für das Quartal alle 27 Länder verfügbar sind."],
      ],
      statusLabel: "Aktueller validierter Datenstand",
      dataGenerated: "Schuldendaten abgerufen",
      ratioGenerated: "Schuldenquoten abgerufen",
      coverage: "Abdeckung des gemeinsamen Zeitraums",
      period: "Referenzzeitraum",
    },
    calculation: {
      eyebrow: "04 — Das Modell",
      title: "Der Zähler wandelt eine Quartalsveränderung in eine konstante Rate pro Sekunde um.",
      intro:
        "Es werden keine Annahmen zu Wachstum, Zinsen oder Politik hinzugefügt. Das Modell verteilt ausschließlich die jüngste beobachtete Veränderung über die Zeit und führt diese Rate nach dem neuesten Quartalsende fort.",
      rateLabel: "Modellierte Rate",
      rateFormula: "(neuester offizieller Schuldenstand − vorheriger offizieller Schuldenstand) ÷ Sekunden zwischen beiden Zeitpunkten",
      estimateLabel: "Schätzung nach dem neuesten Referenzdatum",
      estimateFormula: "neuester offizieller Schuldenstand + Rate × verstrichene Sekunden seit dem neuesten Datum",
      exampleEyebrow: "Rechenbeispiel · aktueller deutscher Datenstand",
      previous: "Vorheriger offizieller Schuldenstand",
      latest: "Neuester offizieller Schuldenstand",
      movement: "Quartalsveränderung",
      elapsed: "Zeit zwischen den Ankerpunkten",
      days: (days) => `${days} Tage`,
      pace: "Modellierte Rate",
      exampleNote:
        "Gerundete Anzeigewerte ergeben möglicherweise nicht exakt dieselbe Rate. Die Berechnung verwendet die vollständig gespeicherten Eurobeträge und UTC-Zeitstempel zum Quartalsende.",
      ratioTitle: "So funktioniert die Live-Schätzung der Schuldenquote",
      ratioText:
        "Eurostats veröffentlichte Quote ist der offizielle Ausgangspunkt. Die optionale Live-Ansicht skaliert diese Quote mit der Veränderung des modellierten Schuldenstands und hält dabei den abgeleiteten BIP-Nenner konstant.",
      ratioFormula: "offizielle Quote × (modellierte Schulden jetzt ÷ offizielle Schulden am Referenzdatum)",
      ratioWarning: "Damit ist sie eine Schätzung der Quote, keine Live-Messung des BIP und keine Prognose.",
    },
    safeguards: {
      eyebrow: "05 — Schutzregeln",
      title: "Das Modell darf anhalten, bevor es irreführen darf.",
      intro:
        "Quartalsdaten können verspätet, revidiert oder unvollständig sein. Vorsichtige Regeln verhindern, dass eine ungewöhnliche Quellenantwort zu einem außer Kontrolle geratenen Zähler wird.",
      cards: [
        ["Feste Obergrenze von €50.000/s", "Jede berechnete Länderrate wird auf einen Bereich zwischen −€50.000 und +€50.000 pro Sekunde begrenzt."],
        ["Stopp bei veralteten Länderdaten", "Liegt ein Land mehr als ein gemeinsames Quartal zurück, bleibt sein letzter offizieller Wert sichtbar, der Zähler wird jedoch eingefroren."],
        ["Rückfall bei fehlender Historie", "Ohne zwei nutzbare Beobachtungen wird die Bewegung auf null gesetzt, bis ein gültiger Vergleich vorliegt."],
        ["Konsistente Zeiträume", "Quartalskennungen werden in UTC-Daten zum Quartalsende umgewandelt, bevor die verstrichene Zeit berechnet wird."],
        ["Gemeinsamer EU-Zeitraum", "Die EU-27-Historie wird nur bei vollständiger Abdeckung aller 27 Länder fortgeschrieben; so werden falsche Gesamtvergleiche verhindert."],
        ["Keine stille Ersetzung", "Offizielle Schulden und offizielle Schuldenquote bleiben getrennte Reihen; eine fehlende Quote wird nicht aus einer anderen Quelle erfunden."],
      ],
    },
    limitations: {
      eyebrow: "06 — Die Schätzung richtig einordnen",
      title: "Präzision auf dem Bildschirm ist keine Präzision in der realen Wirtschaft.",
      intro:
        "Der Zähler hilft bei Größenordnung, Richtung und Vergleich. Er kann weder zeigen, was an einem bestimmten Tag geschah, noch die nächste offizielle Beobachtung vorhersagen.",
      items: [
        ["Schulden bewegen sich nicht gleichmäßig", "Staaten nehmen Schulden auf, tilgen und bewerten sie in einzelnen Transaktionen neu. Ein linearer Zähler ist ein visuelles Modell."],
        ["Eurowerte können Wechselkursbewegungen enthalten", "Für Nicht-Euro-Länder rechnet Eurostat die Schulden zum Wechselkurs des letzten Arbeitstags des Quartals um."],
        ["Offizielle Zeitreihen können revidiert werden", "Nationale Behörden und Eurostat können frühere Quartale nach neuen Informationen, Korrekturen oder methodischen Änderungen überarbeiten."],
        ["Bruttoschulden sind nicht gleich finanzpolitische Gesundheit", "Auch Vermögenswerte, Zinskosten, Laufzeiten, Defizite, Wachstum und Währungsstruktur sind relevant."],
        ["Länderwerte müssen nicht gleichzeitig erscheinen", "Ein Land kann vorübergehend ein älteres offizielles Quartal behalten, solange neuere gemeinsame Daten unvollständig sind."],
        ["Das Modell ist keine Beratung", "EU Debt Map ist eine unabhängige Bildungsvisualisierung, keine offizielle Berichterstattung, Prognose oder Anlageberatung."],
      ],
    },
    updates: {
      eyebrow: "07 — Aktualität und Korrekturen",
      title: "Jede angezeigte Aktualisierung sollte auf ein Quelldatum und eine Methodenversion zurückführbar sein.",
      intro:
        "Eurostat veröffentlicht die vierteljährlichen Staatsschulden in der Regel nach nationaler Meldung und Validierung. Revisionen können auch zwischen regulären Veröffentlichungen eintreffen.",
      cards: [
        ["Offizieller Rhythmus", "Vierteljährlich; die Mitgliedstaaten übermitteln die Daten ungefähr innerhalb von drei Monaten nach Quartalsende."],
        ["Aktualisierung der Website", "Kontrollierte Datenaktualisierung, Validierung und Bereitstellung statt automatischer API-Abfrage im Browser."],
        ["Korrekturen", "Eine korrigierte offizielle Beobachtung ersetzt den gespeicherten Wert, nachdem sie dieselben Validierungsprüfungen bestanden hat."],
      ],
      changelogTitle: "Methodenprotokoll",
      changelog: [
        ["Version 2.0", "30. Aug. 2026", "Ergänzt Live-Quotenlogik, Stopps bei veralteten Daten, genaue Schutzregeln, Revisionen und Wechselkursgrenzen."],
        ["1.2", "Juli 2026", "Dokumentiert validierte Datenstände, offizielle Quoten und Aktualisierungen mit zuletzt bekannten gültigen Länderwerten."],
      ],
    },
    sources: {
      eyebrow: "08 — Methode prüfen",
      title: "Originalquelle, genaue Filter und eine wiederverwendbare Quellenangabe.",
      intro:
        "Die kurze Erklärung bleibt lesbar; die technische Dokumentation ist für Forschende und Entwickelnde nur einen Klick entfernt.",
      sourceCards: [
        ["Primärdatensatz", "Eurostat · gov_10q_ggdebt", "Vierteljährliche Bruttoschulden des Staates"],
        ["Schuldeneinheit", "MIO_EUR", "Durch Multiplikation mit 1.000.000 in Euro umgerechnet"],
        ["Offizielle Quoteneinheit", "PC_GDP", "Direkt aus Eurostats Beobachtung in Prozent des BIP gespeichert"],
        ["Filter", "Q · S13 · GD · EU-27", "Vierteljährlich · Sektor Staat · Bruttoschulden"],
      ],
      detailsTitle: "Technische Abfrage und Pseudocode",
      citationTitle: "Empfohlene Quellenangabe",
      citation:
        "EU Debt Map (2026), ‚Methodik: Eurostat-Daten und Live-Schätzungen der Staatsverschuldung‘, basierend auf Eurostat gov_10q_ggdebt. Abgerufen am 30. August 2026.",
      copyHint: "Bei einer Weiterverwendung der Zahlen sollte neben EU Debt Map auch die ursprüngliche Eurostat-Quelle angegeben werden.",
      linkLabels: ["Offizielle Metadaten", "Datensatz", "JSON-API"],
      primary: "Eurostat-Referenzmetadaten",
      dataset: "Eurostat-Datensatz öffnen",
      api: "Quell-API öffnen",
      nextTitle: "Weiter zu den Daten",
      next: [
        ["EU-27-Karte öffnen", "/de"],
        ["Schuldenquoten vergleichen", "/de/debt-to-gdp"],
        ["Schuldenerklärung lesen", "/de/debt"],
        ["Fiskalregeln ansehen", "/de/stability-and-growth-pact"],
      ],
    },
  },
  fr: {
    base: "/fr",
    locale: "fr-FR",
    schema: {
      headline: "Comment EU Debt Map calcule ses estimations en direct de la dette publique",
      datasetName: "Dette publique trimestrielle d’Eurostat utilisée par EU Debt Map",
      datasetDescription: "Observations trimestrielles validées de la dette brute consolidée des administrations publiques de l’UE-27, utilisées comme points d’ancrage officiels par EU Debt Map.",
      spatialCoverage: "Union européenne",
      home: "Accueil",
      page: "Méthodologie",
    },
    previewLabel: "Étude de conception de la méthodologie · aperçu isolé",
    currentPage: "Voir la page actuelle",
    eyebrow: "Origine des données · Calcul · Limites",
    title: "Des données Eurostat aux estimations en direct de la dette de l’UE.",
    lede:
      "EU Debt Map distingue les faits publiés des mouvements modélisés. Cette page présente chaque étape importante : de l’observation trimestrielle d’origine au chiffre qui évolue à l’écran.",
    heroAction: "Suivre le parcours des données",
    heroNote: "Version 2.0 de la méthode · vérifiée le 30 août 2026",
    sourcePanel: "Le parcours des données",
    sourceSteps: [
      ["01", "Eurostat", "Observations trimestrielles officielles"],
      ["02", "Validation", "Couverture, dates et valeurs contrôlées"],
      ["03", "Instantané", "Dernières données valides stockées localement"],
      ["04", "Modèle", "Variation trimestrielle exprimée par seconde"],
      ["05", "Affichage", "Valeurs officielles et estimations étiquetées séparément"],
    ],
    facts: {
      source: "Source",
      coverage: "Couverture",
      coverageNote: (coverage) => `${coverage}/27 sur la période commune`,
      reference: "Dernière référence",
      referenceNote: "Encours officiel en fin de trimestre",
      fetched: "Dernière récupération",
      fetchedNote: "Instantané stocké et validé",
    },
    navLabel: "Méthodologie",
    nav: ["Vue d’ensemble", "Définition", "Chaîne de données", "Calcul", "Garde-fous", "Limites", "Sources"],
    overview: {
      eyebrow: "01 — La réponse courte",
      title: "Un chiffre officiel. Un modèle clairement identifié.",
      intro:
        "L’encours de dette et le ratio dette/PIB proviennent d’Eurostat. Le compteur en direct, non. EU Debt Map prolonge à rythme constant la variation entre les deux derniers trimestres officiels afin de rendre visibles l’ordre de grandeur et la direction entre deux publications.",
      officialLabel: "Observation officielle",
      officialTitle: "Publiée par Eurostat",
      officialText:
        "Un encours trimestriel daté de dette brute consolidée des administrations publiques, accompagné de la série officielle d’Eurostat en pourcentage du PIB.",
      modelLabel: "Estimation modélisée",
      modelTitle: "Calculée par EU Debt Map",
      modelText:
        "Une prolongation linéaire de la dernière variation trimestrielle observée. Il s’agit d’une représentation pédagogique, et non d’une statistique officielle ou d’une prévision.",
      ruleLabel: "La règle qui s’applique à tout le site",
      rule: "Si un chiffre évolue chaque seconde, il est modélisé. S’il est officiel, sa période de référence Eurostat est indiquée.",
    },
    definition: {
      eyebrow: "02 — Ce qui est mesuré",
      title: "La mesure de la dette est plus étroite — et plus précise — que ‘tout ce qu’un État doit’.",
      intro:
        "EU Debt Map utilise la dette de Maastricht : la dette brute consolidée à la valeur nominale des administrations publiques à la fin de chaque trimestre.",
      includedTitle: "Composantes de la dette de Maastricht",
      included: [
        ["AF.2", "Numéraire et dépôts"],
        ["AF.3", "Titres de créance"],
        ["AF.4", "Crédits"],
      ],
      coverageTitle: "Les administrations publiques comprennent",
      coverage: ["Administration centrale", "Administrations d’États fédérés, le cas échéant", "Administrations locales", "Administrations de sécurité sociale"],
      excludedTitle: "À ne pas interpréter comme",
      excluded: [
        "La dette nette après déduction des actifs publics",
        "Une mesure complète des pensions futures ou d’autres engagements éventuels",
        "Le déficit budgétaire, qui est un flux et non un stock",
        "Un solde comptable public en temps réel",
      ],
      sourceLink: "Lire l’intégralité des métadonnées de référence d’Eurostat",
    },
    pipeline: {
      eyebrow: "03 — De la source à l’écran",
      title: "Une chaîne reproductible, sans dépendance à une API en direct lors des builds ordinaires.",
      intro:
        "La source est distante ; l’environnement de production reste volontairement stable. Les nouvelles observations sont récupérées de manière contrôlée, validées puis enregistrées dans des instantanés locaux avant qu’un déploiement puisse les utiliser.",
      steps: [
        ["Récupérer", "Interroger gov_10q_ggdebt pour les 27 pays de l’UE en MIO_EUR et PC_GDP."],
        ["Normaliser", "Faire correspondre le code EL d’Eurostat à GR et convertir les millions d’euros en euros."],
        ["Valider", "Rejeter les pays manquants, les périodes invalides et les valeurs incompatibles avec l’historique stocké."],
        ["Conserver", "Si un pays manque dans une mise à jour valide, conserver sa dernière observation officielle valide."],
        ["Publier", "Ne faire avancer la période commune de l’UE-27 que lorsque les 27 pays sont disponibles pour le trimestre."],
      ],
      statusLabel: "Instantané validé actuel",
      dataGenerated: "Données de dette récupérées",
      ratioGenerated: "Ratios dette/PIB récupérés",
      coverage: "Couverture de la période commune",
      period: "Période de référence",
    },
    calculation: {
      eyebrow: "04 — Le modèle",
      title: "Le compteur transforme une variation trimestrielle en rythme constant par seconde.",
      intro:
        "Aucune hypothèse de croissance, de taux d’intérêt ou de politique publique n’est ajoutée. Le modèle répartit uniquement la dernière variation observée dans le temps et prolonge ce rythme après la dernière fin de trimestre.",
      rateLabel: "Rythme modélisé",
      rateFormula: "(dernière dette officielle − dette officielle précédente) ÷ secondes entre les deux dates",
      estimateLabel: "Estimation après la dernière date de référence",
      estimateFormula: "dernière dette officielle + rythme × secondes écoulées depuis la dernière date",
      exampleEyebrow: "Exemple de calcul · instantané actuel de l’Allemagne",
      previous: "Dette officielle précédente",
      latest: "Dernière dette officielle",
      movement: "Variation trimestrielle",
      elapsed: "Temps entre les points d’ancrage",
      days: (days) => `${days} jours`,
      pace: "Rythme modélisé",
      exampleNote:
        "Les valeurs d’affichage arrondies peuvent ne pas reproduire exactement le même rythme. Le calcul utilise les montants complets en euros stockés et les horodatages UTC de fin de trimestre.",
      ratioTitle: "Fonctionnement de l’estimation en direct du ratio dette/PIB",
      ratioText:
        "Le ratio publié par Eurostat constitue le point de départ officiel. La vue en direct facultative ajuste ce ratio selon la variation de la dette modélisée tout en maintenant constant le dénominateur implicite du PIB.",
      ratioFormula: "ratio officiel × (dette modélisée actuelle ÷ dette officielle à la date de référence)",
      ratioWarning: "Il s’agit donc d’une estimation du ratio, et non d’une mesure du PIB en direct ou d’une prévision.",
    },
    safeguards: {
      eyebrow: "05 — Garde-fous",
      title: "Le modèle peut s’arrêter avant de risquer d’induire en erreur.",
      intro:
        "Les données trimestrielles peuvent être retardées, révisées ou incomplètes. Des règles prudentes empêchent qu’une réponse inhabituelle de la source produise un compteur incontrôlé.",
      cards: [
        ["Plafond strict de 50 000 €/s", "Tout rythme calculé pour un pays est limité entre −50 000 € et +50 000 € par seconde."],
        ["Gel des pays en retard", "Un pays en retard de plus d’un trimestre commun reste affiché à sa dernière valeur officielle, mais son compteur est gelé."],
        ["Repli en cas d’historique insuffisant", "Sans deux observations utilisables, le mouvement est fixé à zéro jusqu’à ce qu’une comparaison valide soit possible."],
        ["Cohérence des périodes", "Les libellés trimestriels sont convertis en dates UTC de fin de trimestre avant le calcul du temps écoulé."],
        ["Période commune de l’UE", "L’historique de l’UE-27 n’avance qu’avec une couverture complète des 27 pays, ce qui évite de fausses comparaisons de totaux."],
        ["Aucune substitution silencieuse", "La dette officielle et le ratio dette/PIB officiel restent des séries distinctes ; un ratio manquant n’est pas inventé à partir d’une autre source."],
      ],
    },
    limitations: {
      eyebrow: "06 — Interpréter l’estimation avec prudence",
      title: "La précision à l’écran n’est pas celle de l’économie sous-jacente.",
      intro:
        "Le compteur aide à comprendre l’ordre de grandeur, la direction et les comparaisons. Il ne peut ni révéler ce qui s’est produit un jour précis ni prévoir la prochaine observation officielle.",
      items: [
        ["La dette n’évolue pas de façon régulière", "Les administrations émettent, remboursent et réévaluent leur dette par opérations distinctes. Un compteur linéaire est un modèle visuel."],
        ["Les valeurs en euros peuvent intégrer des variations de change", "Pour les pays hors zone euro, Eurostat convertit la dette au taux de change du dernier jour ouvrable du trimestre."],
        ["Les historiques officiels peuvent être révisés", "Les autorités nationales et Eurostat peuvent réviser les trimestres antérieurs après de nouvelles informations, des corrections ou des changements méthodologiques."],
        ["La dette brute ne résume pas la santé des finances publiques", "Les actifs, charges d’intérêt, échéances, déficits, croissance et structure monétaire comptent également."],
        ["Les publications nationales ne sont pas nécessairement simultanées", "Un pays peut conserver temporairement un trimestre officiel plus ancien tant que les nouvelles données communes restent incomplètes."],
        ["Le modèle n’est pas un conseil", "EU Debt Map est une visualisation pédagogique indépendante, et non un rapport officiel, une prévision ou un conseil en investissement."],
      ],
    },
    updates: {
      eyebrow: "07 — Actualité et corrections",
      title: "Chaque mise à jour affichée doit pouvoir être reliée à une date de source et à une version de la méthode.",
      intro:
        "Eurostat publie généralement la dette publique trimestrielle après la transmission et la validation nationales. Des révisions peuvent aussi intervenir entre les publications régulières.",
      cards: [
        ["Rythme officiel", "Trimestriel ; les États membres transmettent les données dans un délai d’environ trois mois après la fin du trimestre."],
        ["Actualisation du site", "Une mise à jour contrôlée des données, suivie d’une validation et d’un déploiement, et non une requête API automatique dans le navigateur."],
        ["Corrections", "Une observation officielle corrigée remplace la valeur stockée après avoir passé les mêmes contrôles de validation."],
      ],
      changelogTitle: "Registre de la méthode",
      changelog: [
        ["Version 2.0", "30 août 2026", "Ajoute la logique du ratio en direct, le gel des données anciennes, les garde-fous exacts, les révisions et les limites liées au change."],
        ["1.2", "juil. 2026", "Documente les instantanés validés, les ratios officiels et les mises à jour fondées sur les dernières données nationales valides."],
      ],
    },
    sources: {
      eyebrow: "08 — Auditer la méthode",
      title: "Source d’origine, filtres exacts et référence réutilisable.",
      intro:
        "L’explication courte reste lisible ; le dossier technique demeure accessible en un clic aux chercheurs et aux développeurs.",
      sourceCards: [
        ["Jeu de données principal", "Eurostat · gov_10q_ggdebt", "Dette brute trimestrielle des administrations publiques"],
        ["Unité de dette", "MIO_EUR", "Conversion en euros par multiplication par 1 000 000"],
        ["Unité officielle du ratio", "PC_GDP", "Stockée directement depuis l’observation d’Eurostat en pourcentage du PIB"],
        ["Filtres", "Q · S13 · GD · UE-27", "Trimestriel · administrations publiques · dette brute"],
      ],
      detailsTitle: "Requête technique et pseudocode",
      citationTitle: "Référence suggérée",
      citation:
        "EU Debt Map (2026), « Méthodologie : données Eurostat et estimations en direct de la dette publique », d’après Eurostat gov_10q_ggdebt. Consulté le 30 août 2026.",
      copyHint: "Lors de la réutilisation des chiffres, citez la source Eurostat d’origine en plus d’EU Debt Map.",
      linkLabels: ["Métadonnées officielles", "Jeu de données", "API JSON"],
      primary: "Métadonnées de référence d’Eurostat",
      dataset: "Ouvrir le jeu de données Eurostat",
      api: "Ouvrir l’API source",
      nextTitle: "Poursuivre avec les données",
      next: [
        ["Ouvrir la carte de l’UE-27", "/fr"],
        ["Comparer les ratios dette/PIB", "/fr/debt-to-gdp"],
        ["Lire l’explication de la dette", "/fr/debt"],
        ["Voir les règles budgétaires", "/fr/stability-and-growth-pact"],
      ],
    },
  },
};

export function getMethodologyCopy(lang = "en") {
  return COPY[lang] || COPY.en;
}
