import { getInterestCopy, interestNumber } from "./interest-copy";

const COPY = {
  en: {
    title: "Government spending and revenue in the EU", shortTitle: "Spending & revenue",
    description: "Compare EU government expenditure, revenue and budget balances as a share of GDP. Official Eurostat annual data, country rankings and historical context.",
    intro: "What governments spend, what they receive, and the balance between the two. Compare the size of public finances across Europe and follow how it changes over time.",
    expenditure: "Government expenditure", revenue: "Government revenue", balance: "Annual accounts balance",
    expenditureRatio: "Expenditure / GDP", revenueRatio: "Revenue / GDP", balanceRatio: "Balance / GDP",
    eu: "EU27 · Eurostat aggregate", euNote: "The EU benchmark uses Eurostat’s published EU27 total and GDP ratios, not a simple average of country percentages. It is not the budget of the EU institutions.",
    mapTitle: "Compare the size and balance of public finances", mapHint: "The map and ranking show the selected GDP ratio. Select a country to compare expenditure, revenue and the fiscal balance together.",
    metric: "Choose a measure", modes: { expenditureRatio: "Government expenditure (% GDP)", revenueRatio: "Government revenue (% GDP)", balanceRatio: "Annual accounts balance (% GDP)" },
    sizeBands: ["Below 35%", "35% to below 45%", "45% to below 55%", "55% or more", "No data"],
    balanceBands: ["Surplus or balance", "Deficit up to 3%", "Deficit greater than 3%", "No data"],
    bandNote: "Spending and revenue colours describe scale, not efficiency or fiscal health. For balances, −3% is the EU reference value, not an automatic legal verdict.",
    rankNote: "Highest selected values first; tied displayed values share a rank (1, 2, 2, 4). Searching preserves EU rank. Changes and differences use percentage points (pp). A high expenditure or revenue rank is not a quality score.",
    rankingTitle: "Compare the 27 national accounts", euGap: "Difference from EU (pp)", previous: "Previous year", change: "Annual change (pp)",
    select: "Explore a country", countryLink: "Explore this country’s government finances", comparisonLink: "Compare spending and revenue in the EU",
    historyTitle: "Expenditure and revenue over time", history: "View all annual figures", countryDetails: "View spending and revenue history", countryTitle: "Government expenditure and revenue",
    pairedTitle: "Expenditure and revenue · % GDP", balanceTitle: "Annual balance · % GDP", historyNote: "Expenditure and revenue share one scale; the balance has its own scale and a zero line. Axes may start above or below zero. Gaps and marked breaks are not connected. Exact amounts, ratios and source flags are in the table.",
    annualContext: "These indicators cover the stated calendar year. Debt and interest elsewhere on the page retain their own periods and sources.",
    missing: "— means missing or not comparable. A missing year is never replaced by a nearby year; changes across marked breaks are withheld.",
    identity: "Revenue − expenditure = net lending (+) / net borrowing (−). The balance shown here is the published B9 from the same annual accounts, not a subtraction of rounded percentages.",
    contextTitle: "Read the two sides of government finances", contextSpending: "What counts as expenditure?", spendingText: "The annual accounts cover the whole general government sector, including public services, benefits, investment and interest. The GDP ratio compares expenditure with the size of the economy; it is not the share of output produced by government or a measure of service quality.",
    contextRevenue: "What counts as revenue?", revenueText: "Revenue includes taxes, social contributions and other receipts. Borrowing is not government revenue. Spending above revenue produces a deficit; revenue above spending produces a surplus. Debt can also change through financial transactions and other adjustments.",
    interestNote: "Interest expenditure is already included in total expenditure. Do not add the interest figure again.", interestLink: "Compare government interest costs", deficitLink: "Compare EDP budget balances",
    sourceTitle: "Sources, calculations and reconciliation", attribution: "Source: Eurostat, gov_10a_main. Visualisation and comparisons by EU Debt Map. Eurostat does not endorse this independent website.",
    definition: "Annual ESA 2010 accounts (A), general government (S13), total expenditure (TE), total revenue (TR), and net lending/net borrowing (B9), in MIO_EUR and PC_GDP. The S13 totals are consolidated within government; summing its subsectors would double-count some flows.",
    formula: "Euro amounts = MIO_EUR × 1,000,000. GDP ratios are published Eurostat values. Changes compare exact calendar years; EU gaps subtract the same-year official EU ratio. Calculated differences inherit source flags and are rounded only for display.",
    validation: "Before publication, revenue minus expenditure is checked against B9, allowing at most €1.5 million or 0.15 percentage points for the three independently rounded inputs. Official EU monetary totals are checked against the country sums. Published figures are never altered to force agreement.",
    revisionTitle: "Why can the deficit page show a different balance?", revisionText: "This page uses gov_10a_main annual accounts. The deficit page retains its separately dated gov_10dd_edpt1 EDP release. Eurostat notes that reporting times and GDP versions can differ. The entries below show the observed differences; they do not establish the reason for each country’s revision.",
    revisionLink: "Compare source versions", revisionCurrent: "Different latest-year balances", revisionHistory: "All observed historical differences", accountsVersion: "Annual accounts · gov_10a_main", edpVersion: "EDP · gov_10dd_edpt1", same: "No differences at the displayed precision for this year.",
    mismatch: (a, b) => `Source difference: annual accounts ${a}; the existing EDP balance is ${b} for the same year. Both source versions remain identifiable.`,
    insight: (name, exp, rev, start, end) => `${name}: expenditure/GDP changed by ${exp} and revenue/GDP by ${rev}, from ${start} to ${end}.`,
    updateText: "An explicit refresh retrieves all six series together, with matching reporting periods and source update times. Country and EU coverage, units, flags, identities and revision safeguards are validated before replacing the local data. Normal visits and builds do not fetch live statistics.",
  },
  nl: {
    title: "Overheidsuitgaven en inkomsten in de EU", shortTitle: "Uitgaven & inkomsten",
    description: "Vergelijk overheidsuitgaven, inkomsten en begrotingssaldi als aandeel van het bbp. Officiële Eurostat-jaarcijfers, landenranglijsten en historische context.",
    intro: "Wat overheden uitgeven, wat ze ontvangen en het saldo daartussen. Vergelijk de omvang van de overheidsfinanciën in Europa en volg de ontwikkeling door de jaren.",
    expenditure: "Overheidsuitgaven", revenue: "Overheidsinkomsten", balance: "Saldo jaarrekeningen",
    expenditureRatio: "Uitgaven / bbp", revenueRatio: "Inkomsten / bbp", balanceRatio: "Saldo / bbp",
    eu: "EU27 · Eurostat-aggregaat", euNote: "De EU-vergelijking gebruikt het gepubliceerde EU27-totaal en de bbp-verhoudingen van Eurostat, geen eenvoudig gemiddelde van landenpercentages. Dit is niet de begroting van de EU-instellingen.",
    mapTitle: "Vergelijk omvang en saldo van de overheidsfinanciën", mapHint: "De kaart en ranglijst tonen de gekozen bbp-verhouding. Kies een land om uitgaven, inkomsten en het begrotingssaldo samen te bekijken.",
    metric: "Kies een maatstaf", modes: { expenditureRatio: "Overheidsuitgaven (% bbp)", revenueRatio: "Overheidsinkomsten (% bbp)", balanceRatio: "Saldo jaarrekeningen (% bbp)" },
    sizeBands: ["Onder 35%", "35% tot onder 45%", "45% tot onder 55%", "55% of meer", "Geen gegevens"],
    balanceBands: ["Overschot of evenwicht", "Tekort tot en met 3%", "Tekort groter dan 3%", "Geen gegevens"],
    bandNote: "Kleuren voor uitgaven en inkomsten beschrijven de omvang, niet de doelmatigheid of financiële gezondheid. Bij saldi is −3% de EU-referentiewaarde, geen automatisch juridisch oordeel.",
    rankNote: "Hoogste gekozen waarden bovenaan; gelijke getoonde waarden delen een rang (1, 2, 2, 4). Zoeken behoudt de EU-rang. Veranderingen en verschillen staan in procentpunten (pp). Een hoge uitgaven- of inkomstenrang is geen kwaliteitsscore.",
    rankingTitle: "Vergelijk de 27 nationale jaarrekeningen", euGap: "Verschil met EU (pp)", previous: "Vorig jaar", change: "Jaarverandering (pp)",
    select: "Bekijk een land", countryLink: "Bekijk de overheidsfinanciën van dit land", comparisonLink: "Vergelijk uitgaven en inkomsten in de EU",
    historyTitle: "Uitgaven en inkomsten door de jaren", history: "Bekijk alle jaarcijfers", countryDetails: "Bekijk de historie van uitgaven en inkomsten", countryTitle: "Overheidsuitgaven en inkomsten",
    pairedTitle: "Uitgaven en inkomsten · % bbp", balanceTitle: "Jaarlijks saldo · % bbp", historyNote: "Uitgaven en inkomsten delen één schaal; het saldo heeft een eigen schaal en nullijn. Assen kunnen boven of onder nul beginnen. Ontbrekende cijfers en gemarkeerde breuken worden niet verbonden. De tabel bevat exacte bedragen, verhoudingen en broncodes.",
    annualContext: "Deze indicatoren betreffen het genoemde kalenderjaar. Schuld en rente elders op de pagina behouden hun eigen perioden en bronnen.",
    missing: "— betekent ontbrekend of niet vergelijkbaar. Een ontbrekend jaar wordt nooit door een nabijgelegen jaar vervangen; veranderingen over gemarkeerde breuken worden weggelaten.",
    identity: "Inkomsten − uitgaven = vorderingenoverschot (+) / vorderingentekort (−). Het getoonde saldo is de gepubliceerde B9 uit dezelfde jaarrekeningen, geen aftrekking van afgeronde percentages.",
    contextTitle: "Lees beide kanten van de overheidsfinanciën", contextSpending: "Wat telt mee als uitgave?", spendingText: "De jaarrekeningen omvatten de hele overheid, waaronder publieke diensten, uitkeringen, investeringen en rente. De bbp-verhouding vergelijkt uitgaven met de omvang van de economie; het is geen aandeel van de productie door de overheid of maatstaf voor de kwaliteit van diensten.",
    contextRevenue: "Wat telt mee als inkomsten?", revenueText: "Inkomsten omvatten belastingen, sociale premies en andere ontvangsten. Geld lenen is geen overheidsinkomst. Uitgaven boven inkomsten geven een tekort; inkomsten boven uitgaven een overschot. Schuld kan daarnaast veranderen door financiële transacties en andere aanpassingen.",
    interestNote: "Rente-uitgaven zijn al onderdeel van de totale uitgaven. Tel het rentebedrag er niet nogmaals bij op.", interestLink: "Vergelijk rentelasten van overheden", deficitLink: "Vergelijk EDP-begrotingssaldi",
    sourceTitle: "Bronnen, berekeningen en aansluiting", attribution: "Bron: Eurostat, gov_10a_main. Visualisatie en vergelijkingen door EU Debt Map. Eurostat onderschrijft deze onafhankelijke website niet.",
    definition: "Jaarrekeningen volgens ESR 2010 (A), totale overheid (S13), totale uitgaven (TE), totale inkomsten (TR) en vorderingenoverschot/vorderingentekort (B9), in MIO_EUR en PC_GDP. De S13-totalen zijn binnen de overheid geconsolideerd; het optellen van deelsectoren zou bepaalde stromen dubbel tellen.",
    formula: "Eurobedragen = MIO_EUR × 1.000.000. Bbp-verhoudingen zijn gepubliceerde Eurostat-waarden. Veranderingen vergelijken exacte kalenderjaren; EU-verschillen trekken de officiële EU-verhouding voor hetzelfde jaar af. Berekende verschillen nemen broncodes over en worden pas voor weergave afgerond.",
    validation: "Voor publicatie wordt inkomsten minus uitgaven getoetst aan B9, met maximaal €1,5 miljoen of 0,15 procentpunt marge voor de drie afzonderlijk afgeronde invoerwaarden. Officiële EU-bedragen worden getoetst aan de landensommen. Gepubliceerde cijfers worden nooit aangepast om aansluiting af te dwingen.",
    revisionTitle: "Waarom kan de tekortpagina een ander saldo tonen?", revisionText: "Deze pagina gebruikt de jaarrekeningen uit gov_10a_main. De tekortpagina behoudt de afzonderlijk gedateerde EDP-publicatie uit gov_10dd_edpt1. Eurostat vermeldt dat rapportagemomenten en bbp-versies kunnen verschillen. Hieronder staan de waargenomen verschillen; die bewijzen niet de reden van elke landenherziening.",
    revisionLink: "Vergelijk bronversies", revisionCurrent: "Afwijkende saldi in het laatste jaar", revisionHistory: "Alle waargenomen historische verschillen", accountsVersion: "Jaarrekeningen · gov_10a_main", edpVersion: "EDP · gov_10dd_edpt1", same: "Geen verschillen op de getoonde precisie voor dit jaar.",
    mismatch: (a, b) => `Bronverschil: jaarrekeningen ${a}; het bestaande EDP-saldo is ${b} voor hetzelfde jaar. Beide bronversies blijven herkenbaar.`,
    insight: (name, exp, rev, start, end) => `${name}: uitgaven/bbp veranderde met ${exp} en inkomsten/bbp met ${rev}, van ${start} tot ${end}.`,
    updateText: "Een expliciete verversing haalt alle zes reeksen samen op, met gelijke verslagperioden en bronbijwerktijden. Landen- en EU-dekking, eenheden, broncodes, aansluitingen en herzieningswaarborgen worden gecontroleerd vóór vervanging van de lokale gegevens. Normale bezoeken en builds halen geen live statistieken op.",
  },
  de: {
    title: "Staatsausgaben und Staatseinnahmen in der EU", shortTitle: "Ausgaben & Einnahmen",
    description: "Staatliche Ausgaben, Einnahmen und Finanzierungssalden im Verhältnis zum BIP vergleichen. Jährliche Eurostat-Daten, Länderranglisten und historische Einordnung.",
    intro: "Was der Staat ausgibt, was er einnimmt und welcher Saldo daraus entsteht. Vergleichen Sie die öffentlichen Finanzen Europas und ihre Entwicklung im Zeitverlauf.",
    expenditure: "Staatsausgaben", revenue: "Staatseinnahmen", balance: "Saldo der Jahresrechnung",
    expenditureRatio: "Ausgaben / BIP", revenueRatio: "Einnahmen / BIP", balanceRatio: "Saldo / BIP",
    eu: "EU27 · Eurostat-Aggregat", euNote: "Der EU-Vergleich verwendet das veröffentlichte EU27-Aggregat und die BIP-Quoten von Eurostat, keinen einfachen Durchschnitt der Länderquoten. Es handelt sich nicht um den Haushalt der EU-Institutionen.",
    mapTitle: "Umfang und Saldo der Staatsfinanzen vergleichen", mapHint: "Karte und Rangliste zeigen die gewählte BIP-Quote. Wählen Sie ein Land, um Ausgaben, Einnahmen und Finanzierungssaldo zusammen zu betrachten.",
    metric: "Kennzahl wählen", modes: { expenditureRatio: "Staatsausgaben (% BIP)", revenueRatio: "Staatseinnahmen (% BIP)", balanceRatio: "Saldo der Jahresrechnung (% BIP)" },
    sizeBands: ["Unter 35%", "35% bis unter 45%", "45% bis unter 55%", "55% oder mehr", "Keine Daten"],
    balanceBands: ["Überschuss oder Ausgleich", "Defizit bis 3%", "Defizit über 3%", "Keine Daten"],
    bandNote: "Ausgaben- und Einnahmenfarben beschreiben den Umfang, nicht Effizienz oder finanzielle Gesundheit. Bei Salden ist −3% der EU-Referenzwert, kein automatisches rechtliches Urteil.",
    rankNote: "Höchste gewählte Werte zuerst; gleiche angezeigte Werte teilen einen Rang (1, 2, 2, 4). Die Suche erhält den EU-Rang. Änderungen und Abstände stehen in Prozentpunkten (pp). Ein hoher Ausgaben- oder Einnahmenrang ist kein Qualitätsmaß.",
    rankingTitle: "Die 27 nationalen Jahresrechnungen vergleichen", euGap: "Abstand zur EU (pp)", previous: "Vorjahr", change: "Jahresänderung (pp)",
    select: "Land auswählen", countryLink: "Staatsfinanzen dieses Landes ansehen", comparisonLink: "Ausgaben und Einnahmen in der EU vergleichen",
    historyTitle: "Ausgaben und Einnahmen im Zeitverlauf", history: "Alle Jahreswerte ansehen", countryDetails: "Verlauf der Ausgaben und Einnahmen ansehen", countryTitle: "Staatsausgaben und Staatseinnahmen",
    pairedTitle: "Ausgaben und Einnahmen · % BIP", balanceTitle: "Jährlicher Saldo · % BIP", historyNote: "Ausgaben und Einnahmen teilen eine Skala; der Saldo hat eine eigene Skala und eine Nulllinie. Achsen können ober- oder unterhalb von null beginnen. Lücken und markierte Brüche werden nicht verbunden. Die Tabelle enthält genaue Beträge, Quoten und Quellencodes.",
    annualContext: "Diese Kennzahlen betreffen das angegebene Kalenderjahr. Schulden und Zinsen an anderer Stelle behalten ihre eigenen Zeiträume und Quellen.",
    missing: "— bedeutet fehlend oder nicht vergleichbar. Ein fehlendes Jahr wird nie durch ein benachbartes ersetzt; Änderungen über markierte Brüche werden nicht ausgewiesen.",
    identity: "Einnahmen − Ausgaben = Finanzierungssaldo, positiv bei Überschuss und negativ bei Defizit. Gezeigt wird der veröffentlichte B9 derselben Jahresrechnung, keine Subtraktion gerundeter Quoten.",
    contextTitle: "Beide Seiten der Staatsfinanzen lesen", contextSpending: "Was zählt als Ausgabe?", spendingText: "Die Jahresrechnungen umfassen den gesamten Staat, darunter öffentliche Dienste, Sozialleistungen, Investitionen und Zinsen. Die BIP-Quote setzt Ausgaben ins Verhältnis zur Wirtschaftsleistung; sie ist weder der staatlich erzeugte Produktionsanteil noch ein Maß für die Qualität öffentlicher Dienste.",
    contextRevenue: "Was zählt als Einnahme?", revenueText: "Einnahmen umfassen Steuern, Sozialbeiträge und andere Erträge. Kreditaufnahme ist keine Staatseinnahme. Übersteigen die Ausgaben die Einnahmen, entsteht ein Defizit; im umgekehrten Fall ein Überschuss. Schulden können sich außerdem durch Finanztransaktionen und andere Anpassungen ändern.",
    interestNote: "Zinsausgaben sind bereits in den Gesamtausgaben enthalten. Addieren Sie den Zinsbetrag nicht nochmals.", interestLink: "Staatliche Zinsausgaben vergleichen", deficitLink: "EDP-Finanzierungssalden vergleichen",
    sourceTitle: "Quellen, Berechnungen und Abstimmung", attribution: "Quelle: Eurostat, gov_10a_main. Visualisierung und Vergleiche von EU Debt Map. Eurostat unterstützt diese unabhängige Website nicht offiziell.",
    definition: "Jährliche ESVG-2010-Rechnungen (A), Staat insgesamt (S13), Gesamtausgaben (TE), Gesamteinnahmen (TR) und Finanzierungssaldo (B9), in MIO_EUR und PC_GDP. Die S13-Summen sind innerhalb des Staates konsolidiert; eine Addition der Teilsektoren würde bestimmte Ströme doppelt zählen.",
    formula: "Eurobeträge = MIO_EUR × 1.000.000. BIP-Quoten sind veröffentlichte Eurostat-Werte. Änderungen vergleichen genau bestimmte Kalenderjahre; EU-Abstände ziehen die offizielle EU-Quote desselben Jahres ab. Berechnete Differenzen übernehmen Quellencodes und werden erst zur Anzeige gerundet.",
    validation: "Vor Veröffentlichung wird Einnahmen minus Ausgaben mit B9 abgeglichen, mit höchstens 1,5 Mio. € oder 0,15 Prozentpunkten Toleranz für drei unabhängig gerundete Eingaben. Offizielle EU-Beträge werden mit Ländersummen verglichen. Veröffentlichte Werte werden nie verändert, um Übereinstimmung zu erzwingen.",
    revisionTitle: "Warum kann die Defizitseite einen anderen Saldo zeigen?", revisionText: "Diese Seite verwendet Jahresrechnungen aus gov_10a_main. Die Defizitseite behält die separat datierte EDP-Veröffentlichung aus gov_10dd_edpt1. Laut Eurostat können Meldezeitpunkte und BIP-Datenstände abweichen. Unten stehen beobachtete Unterschiede; sie belegen nicht den Grund jeder Länderrevision.",
    revisionLink: "Quellenstände vergleichen", revisionCurrent: "Abweichende Salden im jüngsten Jahr", revisionHistory: "Alle beobachteten historischen Unterschiede", accountsVersion: "Jahresrechnungen · gov_10a_main", edpVersion: "EDP · gov_10dd_edpt1", same: "Keine Unterschiede bei der angezeigten Genauigkeit für dieses Jahr.",
    mismatch: (a, b) => `Quellenunterschied: Jahresrechnung ${a}; der bisherige EDP-Saldo ist ${b} für dasselbe Jahr. Beide Quellenstände bleiben erkennbar.`,
    insight: (name, exp, rev, start, end) => `${name}: Ausgaben/BIP veränderte sich um ${exp} und Einnahmen/BIP um ${rev}, von ${start} bis ${end}.`,
    updateText: "Eine ausdrückliche Aktualisierung lädt alle sechs Reihen gemeinsam, mit gleichen Berichtszeiträumen und Quellenständen. Länder- und EU-Abdeckung, Einheiten, Codes, Identitäten und Revisionsregeln werden vor Ersetzen der lokalen Daten geprüft. Normale Besuche und Builds laden keine Live-Statistiken.",
  },
  fr: {
    title: "Dépenses et recettes publiques dans l’UE", shortTitle: "Dépenses & recettes",
    description: "Comparer les dépenses, recettes et soldes publics en pourcentage du PIB. Données annuelles Eurostat, classements nationaux et contexte historique.",
    intro: "Ce que les administrations publiques dépensent, ce qu’elles reçoivent et le solde qui en résulte. Comparez les finances publiques en Europe et leur évolution au fil des années.",
    expenditure: "Dépenses publiques", revenue: "Recettes publiques", balance: "Solde des comptes annuels",
    expenditureRatio: "Dépenses / PIB", revenueRatio: "Recettes / PIB", balanceRatio: "Solde / PIB",
    eu: "UE27 · agrégat Eurostat", euNote: "La comparaison européenne utilise l’agrégat UE27 et les ratios au PIB publiés par Eurostat, pas une moyenne simple des pourcentages nationaux. Il ne s’agit pas du budget des institutions de l’UE.",
    mapTitle: "Comparer l’ampleur et le solde des finances publiques", mapHint: "La carte et le classement montrent le ratio au PIB choisi. Sélectionnez un pays pour examiner ensemble dépenses, recettes et solde public.",
    metric: "Choisir un indicateur", modes: { expenditureRatio: "Dépenses publiques (% PIB)", revenueRatio: "Recettes publiques (% PIB)", balanceRatio: "Solde des comptes annuels (% PIB)" },
    sizeBands: ["Moins de 35%", "35% à moins de 45%", "45% à moins de 55%", "55% ou plus", "Données absentes"],
    balanceBands: ["Excédent ou équilibre", "Déficit jusqu’à 3%", "Déficit supérieur à 3%", "Données absentes"],
    bandNote: "Les couleurs des dépenses et recettes décrivent leur ampleur, pas leur efficacité ni la santé financière. Pour les soldes, −3% est la valeur de référence de l’UE, sans verdict juridique automatique.",
    rankNote: "Les valeurs choisies les plus élevées arrivent en tête ; les valeurs affichées identiques partagent un rang (1, 2, 2, 4). La recherche conserve le rang européen. Variations et écarts sont en points de pourcentage (pp). Un rang élevé de dépenses ou de recettes n’est pas une note de qualité.",
    rankingTitle: "Comparer les 27 comptes annuels nationaux", euGap: "Écart avec l’UE (pp)", previous: "Année précédente", change: "Variation annuelle (pp)",
    select: "Explorer un pays", countryLink: "Explorer les finances publiques de ce pays", comparisonLink: "Comparer dépenses et recettes dans l’UE",
    historyTitle: "Dépenses et recettes au fil des années", history: "Voir toutes les valeurs annuelles", countryDetails: "Voir l’historique des dépenses et recettes", countryTitle: "Dépenses et recettes publiques",
    pairedTitle: "Dépenses et recettes · % PIB", balanceTitle: "Solde annuel · % PIB", historyNote: "Dépenses et recettes partagent une échelle ; le solde possède sa propre échelle et une ligne zéro. Les axes peuvent commencer au-dessus ou au-dessous de zéro. Les lacunes et ruptures signalées ne sont pas reliées. Le tableau contient montants exacts, ratios et codes sources.",
    annualContext: "Ces indicateurs concernent l’année civile indiquée. La dette et les intérêts ailleurs sur la page conservent leurs propres périodes et sources.",
    missing: "— indique une donnée absente ou non comparable. Une année manquante n’est jamais remplacée par une année voisine ; les variations traversant des ruptures signalées ne sont pas affichées.",
    identity: "Recettes − dépenses = capacité (+) / besoin (−) de financement. Le solde affiché est le B9 publié dans les mêmes comptes annuels, pas la soustraction de pourcentages arrondis.",
    contextTitle: "Lire les deux côtés des finances publiques", contextSpending: "Quelles dépenses sont incluses ?", spendingText: "Les comptes annuels couvrent toutes les administrations publiques, notamment services publics, prestations, investissements et intérêts. Le ratio au PIB situe les dépenses par rapport à l’économie ; ce n’est ni la part de production publique ni une mesure de la qualité des services.",
    contextRevenue: "Quelles recettes sont incluses ?", revenueText: "Les recettes comprennent impôts, cotisations sociales et autres revenus. Emprunter n’est pas une recette publique. Des dépenses supérieures aux recettes créent un déficit ; l’inverse produit un excédent. La dette peut aussi varier par des transactions financières et d’autres ajustements.",
    interestNote: "Les intérêts sont déjà compris dans les dépenses totales. N’ajoutez pas une seconde fois leur montant.", interestLink: "Comparer les charges d’intérêts publiques", deficitLink: "Comparer les soldes publics PDE",
    sourceTitle: "Sources, calculs et rapprochement", attribution: "Source : Eurostat, gov_10a_main. Visualisation et comparaisons par EU Debt Map. Eurostat ne cautionne pas ce site indépendant.",
    definition: "Comptes annuels SEC 2010 (A), administrations publiques (S13), dépenses totales (TE), recettes totales (TR) et capacité/besoin de financement (B9), en MIO_EUR et PC_GDP. Les totaux S13 sont consolidés entre administrations ; additionner les sous-secteurs compterait certains flux deux fois.",
    formula: "Montants en euros = MIO_EUR × 1 000 000. Les ratios au PIB sont publiés par Eurostat. Les variations comparent des années civiles précises ; les écarts européens soustraient le ratio officiel de l’UE de la même année. Les différences calculées héritent des codes sources et sont arrondies à l’affichage.",
    validation: "Avant publication, recettes moins dépenses est comparé à B9, avec au maximum 1,5 million € ou 0,15 point de pourcentage de tolérance pour trois données arrondies séparément. Les montants officiels de l’UE sont comparés aux sommes nationales. Aucun chiffre publié n’est modifié pour imposer une égalité.",
    revisionTitle: "Pourquoi la page des déficits peut-elle montrer un autre solde ?", revisionText: "Cette page utilise les comptes annuels gov_10a_main. La page des déficits conserve la publication PDE gov_10dd_edpt1 datée séparément. Eurostat indique que dates de transmission et versions du PIB peuvent différer. Les écarts observés ci-dessous ne démontrent pas la cause de chaque révision nationale.",
    revisionLink: "Comparer les versions des sources", revisionCurrent: "Soldes différents pour l’année la plus récente", revisionHistory: "Tous les écarts historiques observés", accountsVersion: "Comptes annuels · gov_10a_main", edpVersion: "PDE · gov_10dd_edpt1", same: "Aucun écart à la précision affichée pour cette année.",
    mismatch: (a, b) => `Écart entre sources : comptes annuels ${a} ; le solde PDE existant est ${b} pour la même année. Les deux versions restent identifiables.`,
    insight: (name, exp, rev, start, end) => `${name} : dépenses/PIB a varié de ${exp} et recettes/PIB de ${rev}, de ${start} à ${end}.`,
    updateText: "Une actualisation explicite récupère les six séries ensemble, avec périodes et dates sources identiques. Couverture nationale et européenne, unités, codes, identités et règles de révision sont vérifiés avant de remplacer les données locales. Visites et builds ordinaires ne chargent pas de statistiques en direct.",
  },
};
export const getAccountsCopy = lang => ({ ...getInterestCopy(lang), ...(COPY[lang] || COPY.en) });
export const accountNumber = interestNumber;
export const accountDate = (value, lang) => new Intl.DateTimeFormat(getAccountsCopy(lang).locale, { dateStyle: "long", timeZone: "UTC" }).format(new Date(value));
