const COPY = {
  en: {
    locale: "en-GB", title: "Government debt growth in the EU", shortTitle: "Debt growth", description: "Compare changes in government debt across 27 EU countries over 1, 5 and 10 years. Separate growth in euros from changes in debt-to-GDP using official Eurostat history.",
    eyebrow: "European government finances", intro: "A larger debt stock can coexist with a lower debt ratio. Compare where debt has risen or fallen, in euros and relative to GDP, over exact historical periods.",
    official: "EU Debt Map calculations · official quarterly Eurostat inputs", latest: "Latest quarter", horizon: "Comparison period", years: "years", oneYear: "1 year", countries: "Countries", ranking: "How debt has changed", sort: "Rank countries by",
    modes: {percent:"Fastest debt growth (%)",absolute:"Largest debt change (€)",ratioUp:"Largest debt/GDP increase (pp)",ratioDown:"Largest debt/GDP decline (pp)"},
    debt: "Government debt", ratio: "Debt / GDP", amount: "Change in euros", percent: "Debt growth (%)", pp: "Debt/GDP change (pp)", start: "Start", end: "End", rank: "EU rank", country: "Country", search: "Find a country", shown: "Countries shown", noResults: "No matching countries.",
    rankNote: "Rank applies to the selected measure and period. Equal displayed changes share a rank (1, 2, 2, 4); search keeps ranks fixed. Percentages and percentage points use one decimal. A ranking may include decreases as well as increases; read the sign.",
    select: "Explore a country", trend: "Two views of the same debt", chartDebt: "Debt stock in euros", chartRatio: "Official debt-to-GDP ratio", chartNote: "Each chart has its own labelled vertical scale. Gaps and flagged breaks are not joined. The table provides the exact quarterly values.", history: "View quarterly values", quarter: "Quarter", countryLink: "Explore this country’s finances", comparisonLink: "Compare debt growth across the EU", countryTitle: "Debt over 1, 5 and 10 years", countryDetails: "View ten-year charts and source values",
    divergence: "Debt rose in euros while the debt-to-GDP ratio fell over this period.", insight: (name,amount,percent,pp,start,end)=>`${name}: debt changed by ${amount} (${percent}) and debt/GDP by ${pp}, from ${start} to ${end}.`,
    missing: "— = not comparable: an endpoint is missing, the series has a flagged break/definition difference, or the percentage base is zero. No nearby quarter is substituted.",
    flags: "Eurostat flags are retained: p = provisional, e = estimated, b = break, d = definition differs. Calculations inherit input uncertainty. Comparisons crossing b/d flags are withheld; forecasts are excluded. Other source codes remain visible; revisions are possible even without a flag.",
    contextTitle: "More euros is not always a higher debt ratio", contextDebt: "A stock, not an annual deficit", contextDebtText: "The euro change is the ending debt stock minus the starting stock. Percentage growth divides this change by the starting debt. It is the total change over the selected period, not an annual growth rate or CAGR. Financial transactions and valuation effects mean that debt growth is not simply the sum of budget deficits.",
    contextRatio: "A different denominator", contextRatioText: "The ratio change subtracts the two published debt-to-GDP percentages, giving percentage points. A larger nominal economy can reduce this ratio even as debt in euros rises. This observation does not by itself establish why a ratio changed or whether debt is sustainable.",
    fx: "Euro amounts are nominal, not inflation-adjusted. For non-euro countries, movements in the quarter-end exchange rate can change euro debt without the same change in national-currency debt. EU27 membership is held fixed across the historical comparison.",
    sourceTitle: "Source and calculations", method: "Methodology", updated: "Updated by Eurostat", accessed: "Accessed", attribution: "Source: Eurostat, gov_10q_ggdebt. Visualisation and calculations by EU Debt Map. Eurostat does not endorse this independent website.",
    definition: "Quarterly (Q), general government (S13), consolidated gross debt at nominal value (GD), million euros (MIO_EUR) and official percent of GDP (PC_GDP). Both series use the same reporting quarters and source vintage.",
    formula: "Euro change = end − start. Debt growth (%) = (end − start) / start × 100. Debt/GDP change (pp) = ending ratio − starting ratio. Endpoints are the same quarter exactly 1, 5 or 10 years apart; 10 years needs 41 quarterly observations.",
    updateText: "Explicit updates fetch and validate both series together, then replace one local snapshot. Builds and visits use saved data. The latest quarter must cover all 27 countries. Older gaps remain missing; a failed or regressed update preserves the previous snapshot. The existing EU five-year chart requires 21 complete, comparable debt observations for every country.",
    api: "API query", balanceLink: "Compare budget balances", debtLink: "View the EU debt map", overviewFlags: "Official quarterly figures; some inputs are provisional or estimated. Source and calculations",
  },
  nl: {
    locale: "nl-NL", title: "Groei van overheidsschuld in de EU", shortTitle: "Schuldgroei", description: "Vergelijk de verandering van overheidsschuld in 27 EU-landen over 1, 5 en 10 jaar. Bekijk eurogroei en veranderingen in schuld/bbp apart, op basis van Eurostat.",
    eyebrow: "Europese overheidsfinanciën", intro: "Een hogere schuld kan samengaan met een lagere schuldquote. Vergelijk waar de schuld stijgt of daalt, in euro’s en ten opzichte van het bbp, over precies afgebakende periodes.",
    official: "Berekeningen EU Debt Map · officiële Eurostat-kwartaalcijfers", latest: "Laatste kwartaal", horizon: "Vergelijkingsperiode", years: "jaar", oneYear: "1 jaar", countries: "Landen", ranking: "Hoe de schuld is veranderd", sort: "Rangschik landen op",
    modes: {percent:"Snelste schuldgroei (%)",absolute:"Grootste schuldverandering (€)",ratioUp:"Grootste stijging schuld/bbp (pp)",ratioDown:"Grootste daling schuld/bbp (pp)"},
    debt: "Overheidsschuld", ratio: "Schuld / bbp", amount: "Verandering in euro’s", percent: "Schuldgroei (%)", pp: "Verandering schuld/bbp (pp)", start: "Begin", end: "Einde", rank: "EU-rang", country: "Land", search: "Zoek een land", shown: "Getoonde landen", noResults: "Geen landen gevonden.",
    rankNote: "De rang hoort bij de gekozen maatstaf en periode. Gelijke getoonde veranderingen delen een rang (1, 2, 2, 4); zoeken verandert de rang niet. Percentages en procentpunten hebben één decimaal. Een ranglijst kan zowel dalingen als stijgingen bevatten; let op het teken.",
    select: "Bekijk een land", trend: "Twee blikken op dezelfde schuld", chartDebt: "Schuldstand in euro’s", chartRatio: "Officiële schuld/bbp-verhouding", chartNote: "Elke grafiek heeft een eigen, benoemde verticale schaal. Ontbrekende cijfers en gemarkeerde breuken worden niet verbonden. De tabel bevat de exacte kwartaalcijfers.", history: "Bekijk de kwartaalcijfers", quarter: "Kwartaal", countryLink: "Bekijk de overheidsfinanciën van dit land", comparisonLink: "Vergelijk schuldgroei in de EU", countryTitle: "Schuld over 1, 5 en 10 jaar", countryDetails: "Bekijk tienjaarsgrafieken en broncijfers",
    divergence: "De schuld steeg in euro’s, terwijl de schuld/bbp-verhouding in deze periode daalde.", insight: (name,amount,percent,pp,start,end)=>`${name}: de schuld veranderde met ${amount} (${percent}) en schuld/bbp met ${pp}, van ${start} tot ${end}.`,
    missing: "— = niet vergelijkbaar: een eindpunt ontbreekt, de reeks bevat een gemarkeerde breuk/definitieverschil of de procentuele uitgangswaarde is nul. Een ander kwartaal wordt niet als vervanging gebruikt.",
    flags: "Eurostat-codes blijven behouden: p = voorlopig, e = geraamd, b = reeksbreuk, d = afwijkende definitie. Berekeningen nemen de brononzekerheid over. Vergelijkingen over b/d-markeringen worden weggelaten; prognoses worden uitgesloten. Andere broncodes blijven zichtbaar; herzieningen zijn ook zonder code mogelijk.",
    contextTitle: "Meer euro’s betekent niet altijd een hogere schuldquote", contextDebt: "Een schuldstand, geen jaartekort", contextDebtText: "De euroverandering is de eindschuld min de beginschuld. Procentuele groei deelt die verandering door de beginschuld. Het is de totale verandering over de gekozen periode, geen jaarlijkse groeivoet of CAGR. Financiële transacties en waarderingseffecten maken dat schuldgroei niet simpelweg de som van begrotingstekorten is.",
    contextRatio: "Een andere noemer", contextRatioText: "De verandering van de schuldquote trekt de twee gepubliceerde schuld/bbp-percentages van elkaar af en wordt uitgedrukt in procentpunten. Een grotere nominale economie kan de quote laten dalen terwijl de schuld in euro’s stijgt. Die waarneming bewijst op zichzelf niet waarom een quote veranderde of dat de schuld houdbaar is.",
    fx: "Eurobedragen zijn nominaal en niet gecorrigeerd voor inflatie. Voor niet-eurolanden kan de wisselkoers aan het kwartaaleinde de euroschuld veranderen zonder dezelfde verandering in nationale valuta. We gebruiken voor alle historische vergelijkingen dezelfde 27 huidige EU-landen.",
    sourceTitle: "Bron en berekeningen", method: "Methodologie", updated: "Bijgewerkt door Eurostat", accessed: "Geraadpleegd", attribution: "Bron: Eurostat, gov_10q_ggdebt. Visualisatie en berekeningen door EU Debt Map. Eurostat onderschrijft deze onafhankelijke website niet.",
    definition: "Kwartaalcijfers (Q), totale overheid (S13), geconsolideerde brutoschuld tegen nominale waarde (GD), miljoen euro (MIO_EUR) en officieel percentage van het bbp (PC_GDP). Beide reeksen gebruiken dezelfde verslagkwartalen en bronversie.",
    formula: "Euroverandering = einde − begin. Schuldgroei (%) = (einde − begin) / begin × 100. Verandering schuld/bbp (pp) = eindquote − beginquote. Eindpunten liggen precies 1, 5 of 10 jaar uit elkaar, in hetzelfde kwartaal; voor 10 jaar zijn 41 kwartaalwaarnemingen nodig.",
    updateText: "Een expliciete update haalt beide reeksen op, controleert ze samen en vervangt één lokale momentopname. Builds en bezoeken gebruiken opgeslagen data. Het laatste kwartaal moet alle 27 landen bevatten. Oudere ontbrekende cijfers blijven ontbreken; een mislukte of teruglopende update behoudt de vorige opslag. De bestaande EU-vijfjaarsgrafiek vereist voor ieder land 21 volledige, vergelijkbare schuldwaarnemingen.",
    api: "API-aanvraag", balanceLink: "Vergelijk begrotingssaldi", debtLink: "Bekijk de EU-schuldenkaart", overviewFlags: "Officiële kwartaalcijfers; sommige broncijfers zijn voorlopig of geraamd. Bron en berekeningen",
  },
  de: {
    locale: "de-DE", title: "Entwicklung der Staatsschulden in der EU", shortTitle: "Schuldenentwicklung", description: "Vergleichen Sie die Schuldenentwicklung von 27 EU-Ländern über 1, 5 und 10 Jahre. Euro-Beträge und Änderungen der Schuldenquote werden anhand offizieller Eurostat-Daten getrennt gezeigt.",
    eyebrow: "Europäische Staatsfinanzen", intro: "Ein höherer Schuldenstand kann mit einer niedrigeren Schuldenquote einhergehen. Vergleichen Sie Anstiege und Rückgänge in Euro und im Verhältnis zum BIP über exakt abgegrenzte Zeiträume.",
    official: "Berechnungen von EU Debt Map · offizielle Eurostat-Quartalsdaten", latest: "Letztes Quartal", horizon: "Vergleichszeitraum", years: "Jahre", oneYear: "1 Jahr", countries: "Länder", ranking: "Wie sich die Schulden verändert haben", sort: "Länder ordnen nach",
    modes: {percent:"Schnellstes Schuldenwachstum (%)",absolute:"Größte Schuldenänderung (€)",ratioUp:"Größter Anstieg Schulden/BIP (Pp.)",ratioDown:"Größter Rückgang Schulden/BIP (Pp.)"},
    debt: "Staatsschulden", ratio: "Schulden / BIP", amount: "Änderung in Euro", percent: "Schuldenwachstum (%)", pp: "Änderung Schulden/BIP (Pp.)", start: "Beginn", end: "Ende", rank: "EU-Rang", country: "Land", search: "Land suchen", shown: "Angezeigte Länder", noResults: "Keine passenden Länder.",
    rankNote: "Der Rang gilt für die gewählte Kennzahl und den Zeitraum. Gleiche angezeigte Änderungen teilen sich einen Rang (1, 2, 2, 4); die Suche ändert ihn nicht. Prozentwerte und Prozentpunkte haben eine Dezimalstelle. Die Rangliste kann Rückgänge und Anstiege enthalten; beachten Sie das Vorzeichen.",
    select: "Land ansehen", trend: "Zwei Perspektiven auf dieselben Schulden", chartDebt: "Schuldenstand in Euro", chartRatio: "Offizielle Schuldenquote", chartNote: "Jeder Chart hat eine eigene beschriftete vertikale Skala. Lücken und markierte Brüche werden nicht verbunden. Die Tabelle enthält die genauen Quartalswerte.", history: "Quartalswerte ansehen", quarter: "Quartal", countryLink: "Staatsfinanzen dieses Landes ansehen", comparisonLink: "Schuldenentwicklung in der EU vergleichen", countryTitle: "Schulden über 1, 5 und 10 Jahre", countryDetails: "Zehnjahrescharts und Quellenwerte ansehen",
    divergence: "Die Schulden stiegen in Euro, während die Schuldenquote in diesem Zeitraum sank.", insight: (name,amount,percent,pp,start,end)=>`${name}: Die Schulden änderten sich um ${amount} (${percent}), Schulden/BIP um ${pp}, von ${start} bis ${end}.`,
    missing: "— = nicht vergleichbar: Ein Endpunkt fehlt, die Reihe enthält einen markierten Bruch/Definitionsunterschied oder der Ausgangswert für die Prozentrechnung ist null. Kein anderes Quartal wird ersatzweise verwendet.",
    flags: "Eurostat-Kennzeichnungen bleiben erhalten: p = vorläufig, e = geschätzt, b = Reihenbruch, d = abweichende Definition. Berechnungen übernehmen die Unsicherheit. Vergleiche über b/d-Markierungen werden nicht ausgewiesen; Prognosen sind ausgeschlossen. Weitere Quellencodes bleiben sichtbar; Revisionen sind auch ohne Code möglich.",
    contextTitle: "Mehr Euro bedeuten nicht immer eine höhere Schuldenquote", contextDebt: "Ein Bestand, kein Jahresdefizit", contextDebtText: "Die Euro-Änderung ist der Endbestand minus Anfangsbestand. Prozentuales Wachstum teilt diese Änderung durch den Anfangsbestand. Es ist die gesamte Änderung im Zeitraum, keine jährliche Wachstumsrate oder CAGR. Finanztransaktionen und Bewertungseffekte bedeuten, dass Schuldenwachstum nicht einfach der Summe der Haushaltsdefizite entspricht.",
    contextRatio: "Ein anderer Nenner", contextRatioText: "Die Änderung der Quote ist die Differenz der veröffentlichten Schulden/BIP-Prozentwerte in Prozentpunkten. Eine größere nominale Wirtschaft kann die Quote senken, obwohl die Euro-Schulden steigen. Diese Beobachtung belegt allein weder die Ursache noch die Tragfähigkeit der Schulden.",
    fx: "Euro-Beträge sind nominal und nicht inflationsbereinigt. Außerhalb des Euroraums können Wechselkurse am Quartalsende die Euro-Schulden verändern, ohne dass die Schulden in Landeswährung im gleichen Maß steigen oder fallen. Der historische Vergleich umfasst durchgehend dieselben heutigen 27 EU-Länder.",
    sourceTitle: "Quelle und Berechnungen", method: "Methodik", updated: "Von Eurostat aktualisiert", accessed: "Abgerufen", attribution: "Quelle: Eurostat, gov_10q_ggdebt. Visualisierung und Berechnungen: EU Debt Map. Eurostat unterstützt oder empfiehlt diese unabhängige Website nicht.",
    definition: "Quartalsdaten (Q), Gesamtstaat (S13), konsolidierte Bruttoschulden zum Nominalwert (GD), Millionen Euro (MIO_EUR) und offizieller BIP-Anteil (PC_GDP). Beide Reihen verwenden dieselben Berichtsquartale und denselben Quellenstand.",
    formula: "Euro-Änderung = Ende − Beginn. Schuldenwachstum (%) = (Ende − Beginn) / Beginn × 100. Änderung Schulden/BIP (Pp.) = Endquote − Anfangsquote. Endpunkte liegen im selben Quartal genau 1, 5 oder 10 Jahre auseinander; 10 Jahre benötigen 41 Quartalswerte.",
    updateText: "Ausdrückliche Aktualisierungen rufen beide Reihen ab, prüfen sie gemeinsam und ersetzen einen lokalen Datenstand. Builds und Aufrufe nutzen gespeicherte Daten. Das letzte Quartal muss alle 27 Länder enthalten. Ältere Lücken bleiben erhalten; fehlgeschlagene oder rückläufige Aktualisierungen behalten den bisherigen Stand. Der bestehende EU-Fünfjahreschart benötigt je Land 21 vollständige, vergleichbare Schuldenwerte.",
    api: "API-Abfrage", balanceLink: "Finanzierungssalden vergleichen", debtLink: "Zur EU-Schuldenkarte", overviewFlags: "Offizielle Quartalsdaten; einige Ausgangsdaten sind vorläufig oder geschätzt. Quelle und Berechnungen",
  },
  fr: {
    locale: "fr-FR", title: "Évolution de la dette publique dans l’UE", shortTitle: "Évolution de la dette", description: "Comparez l’évolution de la dette des 27 pays de l’UE sur 1, 5 et 10 ans. Distinguez les variations en euros et celles du ratio dette/PIB à partir des données Eurostat.",
    eyebrow: "Finances publiques européennes", intro: "Une dette plus élevée peut coexister avec un ratio d’endettement plus faible. Comparez hausses et baisses en euros et par rapport au PIB sur des périodes précisément définies.",
    official: "Calculs d’EU Debt Map · données trimestrielles officielles Eurostat", latest: "Dernier trimestre", horizon: "Période de comparaison", years: "ans", oneYear: "1 an", countries: "Pays", ranking: "Comment la dette a évolué", sort: "Classer les pays selon",
    modes: {percent:"Croissance de la dette la plus rapide (%)",absolute:"Plus forte variation de dette (€)",ratioUp:"Plus forte hausse dette/PIB (pp)",ratioDown:"Plus forte baisse dette/PIB (pp)"},
    debt: "Dette publique", ratio: "Dette / PIB", amount: "Variation en euros", percent: "Croissance de la dette (%)", pp: "Variation dette/PIB (pp)", start: "Début", end: "Fin", rank: "Rang dans l’UE", country: "Pays", search: "Rechercher un pays", shown: "Pays affichés", noResults: "Aucun pays correspondant.",
    rankNote: "Le rang correspond à la mesure et à la période choisies. Les variations affichées identiques partagent un rang (1, 2, 2, 4) ; la recherche le conserve. Pourcentages et points de pourcentage ont une décimale. Le classement peut inclure baisses et hausses ; lisez le signe.",
    select: "Explorer un pays", trend: "Deux regards sur la même dette", chartDebt: "Encours de dette en euros", chartRatio: "Ratio dette/PIB officiel", chartNote: "Chaque graphique possède sa propre échelle verticale indiquée. Les lacunes et ruptures signalées ne sont pas reliées. Le tableau fournit les valeurs trimestrielles exactes.", history: "Voir les valeurs trimestrielles", quarter: "Trimestre", countryLink: "Explorer les finances publiques de ce pays", comparisonLink: "Comparer l’évolution de la dette dans l’UE", countryTitle: "La dette sur 1, 5 et 10 ans", countryDetails: "Voir les graphiques sur dix ans et les valeurs sources",
    divergence: "La dette a augmenté en euros tandis que le ratio dette/PIB a baissé sur cette période.", insight: (name,amount,percent,pp,start,end)=>`${name} : la dette a varié de ${amount} (${percent}) et le ratio dette/PIB de ${pp}, de ${start} à ${end}.`,
    missing: "— = non comparable : une borne manque, la série comporte une rupture/différence de définition signalée, ou la base du pourcentage est nulle. Aucun autre trimestre n’est substitué.",
    flags: "Les codes Eurostat sont conservés : p = provisoire, e = estimé, b = rupture, d = définition différente. Les calculs héritent de l’incertitude. Les comparaisons traversant un code b/d ne sont pas affichées ; les prévisions sont exclues. Les autres codes restent visibles ; des révisions sont possibles sans code.",
    contextTitle: "Plus d’euros ne signifie pas toujours un ratio plus élevé", contextDebt: "Un encours, pas un déficit annuel", contextDebtText: "La variation en euros est l’encours final moins l’encours initial. La croissance en pourcentage divise cette variation par l’encours initial. C’est la variation totale sur la période, pas un taux annuel ou un taux de croissance annuel composé. Les transactions financières et effets de valorisation font que la dette ne varie pas simplement de la somme des déficits.",
    contextRatio: "Un autre dénominateur", contextRatioText: "La variation du ratio soustrait les deux pourcentages dette/PIB publiés, en points de pourcentage. Une économie nominale plus grande peut réduire le ratio malgré une hausse de la dette en euros. Cette observation ne démontre à elle seule ni la cause du changement ni la soutenabilité de la dette.",
    fx: "Les montants en euros sont nominaux, sans correction de l’inflation. Hors zone euro, les taux de change en fin de trimestre peuvent modifier la dette en euros sans variation équivalente en monnaie nationale. Le périmètre historique conserve les mêmes 27 pays actuellement membres de l’UE.",
    sourceTitle: "Source et calculs", method: "Méthodologie", updated: "Mise à jour Eurostat", accessed: "Consulté le", attribution: "Source : Eurostat, gov_10q_ggdebt. Visualisation et calculs : EU Debt Map. Eurostat n’approuve pas ce site indépendant.",
    definition: "Données trimestrielles (Q), administrations publiques (S13), dette brute consolidée à valeur nominale (GD), millions d’euros (MIO_EUR) et pourcentage officiel du PIB (PC_GDP). Les deux séries utilisent les mêmes trimestres et la même version de source.",
    formula: "Variation en euros = fin − début. Croissance de dette (%) = (fin − début) / début × 100. Variation dette/PIB (pp) = ratio final − ratio initial. Les bornes se situent au même trimestre, exactement à 1, 5 ou 10 ans d’intervalle ; 10 ans nécessitent 41 observations trimestrielles.",
    updateText: "Les mises à jour explicites récupèrent et valident les deux séries ensemble, puis remplacent un instantané local. Les compilations et visites utilisent les données sauvegardées. Le dernier trimestre doit couvrir les 27 pays. Les anciennes lacunes restent manquantes ; un échec ou une régression conserve le précédent instantané. Le graphique européen sur cinq ans exige 21 observations de dette complètes et comparables par pays.",
    api: "Requête API", balanceLink: "Comparer les soldes publics", debtLink: "Voir la carte de la dette de l’UE", overviewFlags: "Données trimestrielles officielles ; certaines sont provisoires ou estimées. Source et calculs",
  },
};
export function getGrowthCopy(lang = "en") { return COPY[lang] || COPY.en; }
export function growthNumber(value, lang = "en", type = "eur", signed = false) {
  if (!Number.isFinite(value)) return "—";
  const options = type === "eur" || type === "compact" ? { style: "currency", currency: "EUR", maximumFractionDigits: type === "compact" ? 2 : 0, ...(type === "compact" ? {notation:"compact"} : {}) }
    : {minimumFractionDigits:1,maximumFractionDigits:1};
  const normalized = Math.abs(value) < 0.00001 ? 0 : value;
  return new Intl.NumberFormat(getGrowthCopy(lang).locale, {...options, ...(signed ? {signDisplay:"exceptZero"} : {})}).format(normalized) + (type === "percent" ? "%" : type === "pp" ? (lang === "de" ? " Pp." : " pp") : "");
}
export function growthQuarter(q, lang = "en") { return lang === "fr" ? q.replace(/(\d{4})-Q([1-4])/, "T$2 $1") : q.replace("-", " "); }
export function growthInsight(row, name, lang) {
  if (row.debt.change === null || row.debt.percent === null || row.ratio.change === null) return null;
  return getGrowthCopy(lang).insight(name,growthNumber(row.debt.change,lang,"compact",true),growthNumber(row.debt.percent,lang,"percent",true),growthNumber(row.ratio.change,lang,"pp",true),growthQuarter(row.debt.start,lang),growthQuarter(row.debt.end,lang));
}
