// Auto-generated by scripts/update-eurostat-debt.js
export const EUROSTAT_SNAPSHOT_ID = "2026-07-31T11:54:33.124Z|2026-Q1";
export const EUROSTAT_UPDATED_AT = "2026-07-31T11:54:33.124Z";
export const EUROSTAT_UPDATE_REPORT = {
  "fetchedAt": "2026-07-31T11:54:33.124Z",
  "sourceLatestAvailableQuarter": "2026-Q1",
  "periodCounts": {
    "2026-Q1": 27
  },
  "dominantLatestTime": "2026-Q1",
  "dominantCoverage": 27,
  "latestAvailableTime": "2026-Q1",
  "acceptedCodes": [
    "AT",
    "BE",
    "BG",
    "HR",
    "CY",
    "CZ",
    "DK",
    "EE",
    "FI",
    "FR",
    "DE",
    "GR",
    "HU",
    "IE",
    "IT",
    "LV",
    "LT",
    "LU",
    "MT",
    "NL",
    "PL",
    "PT",
    "RO",
    "SK",
    "SI",
    "ES",
    "SE"
  ],
  "carriedForwardCodes": [],
  "regressedSourceCodes": [],
  "missingCodes": [],
  "staleCodes": [],
  "sourceMissingGeoKeys": [],
  "sourceUnknownGeoKeys": [],
  "latestCompleteHistoryQuarter": "2026-Q1",
  "latestAvailableHistoryQuarter": "2026-Q1"
};
export const EUROSTAT_SERIES = {
  "AT": {
    "latestTime": "2026-Q1",
    "previousTime": "2025-Q4",
    "startValue": 418078500000,
    "endValue": 431411300000,
    "startDateISO": "2025-12-31T23:59:59.000Z",
    "endDateISO": "2026-03-31T23:59:59.000Z",
    "perSecond": 1714.6090534979423,
    "trend": "rising"
  },
  "BE": {
    "latestTime": "2026-Q1",
    "previousTime": "2025-Q4",
    "startValue": 692460000000,
    "endValue": 706581000000,
    "startDateISO": "2025-12-31T23:59:59.000Z",
    "endDateISO": "2026-03-31T23:59:59.000Z",
    "perSecond": 1815.9722222222222,
    "trend": "rising"
  },
  "BG": {
    "latestTime": "2026-Q1",
    "previousTime": "2025-Q4",
    "startValue": 34634900000,
    "endValue": 34232800000.000004,
    "startDateISO": "2025-12-31T23:59:59.000Z",
    "endDateISO": "2026-03-31T23:59:59.000Z",
    "perSecond": -51.71039094650157,
    "trend": "falling"
  },
  "HR": {
    "latestTime": "2026-Q1",
    "previousTime": "2025-Q4",
    "startValue": 52370800000,
    "endValue": 55216100000,
    "startDateISO": "2025-12-31T23:59:59.000Z",
    "endDateISO": "2026-03-31T23:59:59.000Z",
    "perSecond": 365.9079218106996,
    "trend": "rising"
  },
  "CY": {
    "latestTime": "2026-Q1",
    "previousTime": "2025-Q4",
    "startValue": 20078200000,
    "endValue": 20088700000,
    "startDateISO": "2025-12-31T23:59:59.000Z",
    "endDateISO": "2026-03-31T23:59:59.000Z",
    "perSecond": 1.3503086419753085,
    "trend": "rising"
  },
  "CZ": {
    "latestTime": "2026-Q1",
    "previousTime": "2025-Q4",
    "startValue": 156217800000,
    "endValue": 156151000000,
    "startDateISO": "2025-12-31T23:59:59.000Z",
    "endDateISO": "2026-03-31T23:59:59.000Z",
    "perSecond": -8.590534979423868,
    "trend": "falling"
  },
  "DK": {
    "latestTime": "2026-Q1",
    "previousTime": "2025-Q4",
    "startValue": 113615100000,
    "endValue": 112460600000,
    "startDateISO": "2025-12-31T23:59:59.000Z",
    "endDateISO": "2026-03-31T23:59:59.000Z",
    "perSecond": -148.46965020576133,
    "trend": "falling"
  },
  "EE": {
    "latestTime": "2026-Q1",
    "previousTime": "2025-Q4",
    "startValue": 10035200000,
    "endValue": 10645800000,
    "startDateISO": "2025-12-31T23:59:59.000Z",
    "endDateISO": "2026-03-31T23:59:59.000Z",
    "perSecond": 78.52366255144032,
    "trend": "rising"
  },
  "FI": {
    "latestTime": "2026-Q1",
    "previousTime": "2025-Q4",
    "startValue": 249147000000,
    "endValue": 255139000000,
    "startDateISO": "2025-12-31T23:59:59.000Z",
    "endDateISO": "2026-03-31T23:59:59.000Z",
    "perSecond": 770.5761316872428,
    "trend": "rising"
  },
  "FR": {
    "latestTime": "2026-Q1",
    "previousTime": "2025-Q4",
    "startValue": 3460465100000,
    "endValue": 3536067700000,
    "startDateISO": "2025-12-31T23:59:59.000Z",
    "endDateISO": "2026-03-31T23:59:59.000Z",
    "perSecond": 9722.55658436214,
    "trend": "rising"
  },
  "DE": {
    "latestTime": "2026-Q1",
    "previousTime": "2025-Q4",
    "startValue": 2838238900000,
    "endValue": 2902035300000,
    "startDateISO": "2025-12-31T23:59:59.000Z",
    "endDateISO": "2026-03-31T23:59:59.000Z",
    "perSecond": 8204.269547325102,
    "trend": "rising"
  },
  "GR": {
    "latestTime": "2026-Q1",
    "previousTime": "2025-Q4",
    "startValue": 362925000000,
    "endValue": 360106000000,
    "startDateISO": "2025-12-31T23:59:59.000Z",
    "endDateISO": "2026-03-31T23:59:59.000Z",
    "perSecond": -362.525720164609,
    "trend": "falling"
  },
  "HU": {
    "latestTime": "2026-Q1",
    "previousTime": "2025-Q4",
    "startValue": 168539600000,
    "endValue": 179198700000,
    "startDateISO": "2025-12-31T23:59:59.000Z",
    "endDateISO": "2026-03-31T23:59:59.000Z",
    "perSecond": 1370.7690329218108,
    "trend": "rising"
  },
  "IE": {
    "latestTime": "2026-Q1",
    "previousTime": "2025-Q4",
    "startValue": 209894800000,
    "endValue": 215411200000,
    "startDateISO": "2025-12-31T23:59:59.000Z",
    "endDateISO": "2026-03-31T23:59:59.000Z",
    "perSecond": 709.4135802469136,
    "trend": "rising"
  },
  "IT": {
    "latestTime": "2026-Q1",
    "previousTime": "2025-Q4",
    "startValue": 3095887600000,
    "endValue": 3158190600000,
    "startDateISO": "2025-12-31T23:59:59.000Z",
    "endDateISO": "2026-03-31T23:59:59.000Z",
    "perSecond": 8012.2170781893,
    "trend": "rising"
  },
  "LV": {
    "latestTime": "2026-Q1",
    "previousTime": "2025-Q4",
    "startValue": 20173900000,
    "endValue": 20435800000,
    "startDateISO": "2025-12-31T23:59:59.000Z",
    "endDateISO": "2026-03-31T23:59:59.000Z",
    "perSecond": 33.68055555555556,
    "trend": "rising"
  },
  "LT": {
    "latestTime": "2026-Q1",
    "previousTime": "2025-Q4",
    "startValue": 33259000000,
    "endValue": 36259500000,
    "startDateISO": "2025-12-31T23:59:59.000Z",
    "endDateISO": "2026-03-31T23:59:59.000Z",
    "perSecond": 385.8667695473251,
    "trend": "rising"
  },
  "LU": {
    "latestTime": "2026-Q1",
    "previousTime": "2025-Q4",
    "startValue": 23695100000,
    "endValue": 26402100000,
    "startDateISO": "2025-12-31T23:59:59.000Z",
    "endDateISO": "2026-03-31T23:59:59.000Z",
    "perSecond": 348.12242798353907,
    "trend": "rising"
  },
  "MT": {
    "latestTime": "2026-Q1",
    "previousTime": "2025-Q4",
    "startValue": 11397100000,
    "endValue": 11457600000,
    "startDateISO": "2025-12-31T23:59:59.000Z",
    "endDateISO": "2026-03-31T23:59:59.000Z",
    "perSecond": 7.780349794238683,
    "trend": "rising"
  },
  "NL": {
    "latestTime": "2026-Q1",
    "previousTime": "2025-Q4",
    "startValue": 523720000000,
    "endValue": 517377000000,
    "startDateISO": "2025-12-31T23:59:59.000Z",
    "endDateISO": "2026-03-31T23:59:59.000Z",
    "perSecond": -815.7150205761317,
    "trend": "falling"
  },
  "PL": {
    "latestTime": "2026-Q1",
    "previousTime": "2025-Q4",
    "startValue": 553221500000,
    "endValue": 569889500000,
    "startDateISO": "2025-12-31T23:59:59.000Z",
    "endDateISO": "2026-03-31T23:59:59.000Z",
    "perSecond": 2143.5185185185187,
    "trend": "rising"
  },
  "PT": {
    "latestTime": "2026-Q1",
    "previousTime": "2025-Q4",
    "startValue": 275062800000,
    "endValue": 283106500000,
    "startDateISO": "2025-12-31T23:59:59.000Z",
    "endDateISO": "2026-03-31T23:59:59.000Z",
    "perSecond": 1034.4264403292182,
    "trend": "rising"
  },
  "RO": {
    "latestTime": "2026-Q1",
    "previousTime": "2025-Q4",
    "startValue": 223144700000,
    "endValue": 229426700000,
    "startDateISO": "2025-12-31T23:59:59.000Z",
    "endDateISO": "2026-03-31T23:59:59.000Z",
    "perSecond": 807.8703703703703,
    "trend": "rising"
  },
  "SK": {
    "latestTime": "2026-Q1",
    "previousTime": "2025-Q4",
    "startValue": 83956800000,
    "endValue": 86802600000,
    "startDateISO": "2025-12-31T23:59:59.000Z",
    "endDateISO": "2026-03-31T23:59:59.000Z",
    "perSecond": 365.97222222222223,
    "trend": "rising"
  },
  "SI": {
    "latestTime": "2026-Q1",
    "previousTime": "2025-Q4",
    "startValue": 46323600000,
    "endValue": 46314900000,
    "startDateISO": "2025-12-31T23:59:59.000Z",
    "endDateISO": "2026-03-31T23:59:59.000Z",
    "perSecond": -1.1188271604938271,
    "trend": "falling"
  },
  "ES": {
    "latestTime": "2026-Q1",
    "previousTime": "2025-Q4",
    "startValue": 1698225000000,
    "endValue": 1739501000000,
    "startDateISO": "2025-12-31T23:59:59.000Z",
    "endDateISO": "2026-03-31T23:59:59.000Z",
    "perSecond": 5308.127572016461,
    "trend": "rising"
  },
  "SE": {
    "latestTime": "2026-Q1",
    "previousTime": "2025-Q4",
    "startValue": 216031000000,
    "endValue": 213930900000,
    "startDateISO": "2025-12-31T23:59:59.000Z",
    "endDateISO": "2026-03-31T23:59:59.000Z",
    "perSecond": -270.07458847736626,
    "trend": "falling"
  }
};
