// Auto-generated by scripts/fetch-eurostat.js
export const EUROSTAT_UPDATED_AT = "2026-04-22T15:02:41.326Z";
export const EUROSTAT_SERIES = {
  "BE": {
    "latestTime": "2025-Q4",
    "previousTime": "2025-Q3",
    "startValue": 680800000000,
    "endValue": 692461000000,
    "startDateISO": null,
    "endDateISO": null,
    "perSecond": 11661000000,
    "trend": "rising"
  },
  "BG": {
    "latestTime": "2025-Q4",
    "previousTime": "2025-Q3",
    "startValue": 31824900000,
    "endValue": 34634900000,
    "startDateISO": null,
    "endDateISO": null,
    "perSecond": 2810000000,
    "trend": "rising"
  },
  "CZ": {
    "latestTime": "2025-Q4",
    "previousTime": "2025-Q3",
    "startValue": 148896300000,
    "endValue": 156217800000,
    "startDateISO": null,
    "endDateISO": null,
    "perSecond": 7321500000,
    "trend": "rising"
  },
  "DK": {
    "latestTime": "2025-Q4",
    "previousTime": "2025-Q3",
    "startValue": 120734800000,
    "endValue": 114501500000,
    "startDateISO": null,
    "endDateISO": null,
    "perSecond": -6233300000,
    "trend": "falling"
  },
  "DE": {
    "latestTime": "2025-Q4",
    "previousTime": "2025-Q3",
    "startValue": 2789527600000,
    "endValue": 2838238900000,
    "startDateISO": null,
    "endDateISO": null,
    "perSecond": 48711300000,
    "trend": "rising"
  },
  "EE": {
    "latestTime": "2025-Q4",
    "previousTime": "2025-Q3",
    "startValue": 9414200000,
    "endValue": 10035200000,
    "startDateISO": null,
    "endDateISO": null,
    "perSecond": 621000000,
    "trend": "rising"
  },
  "IE": {
    "latestTime": "2025-Q4",
    "previousTime": "2025-Q3",
    "startValue": 208911500000,
    "endValue": 209902300000,
    "startDateISO": null,
    "endDateISO": null,
    "perSecond": 990800000,
    "trend": "rising"
  },
  "GR": {
    "latestTime": "2025-Q4",
    "previousTime": "2025-Q3",
    "startValue": 367847000000,
    "endValue": 362925000000,
    "startDateISO": null,
    "endDateISO": null,
    "perSecond": -4922000000,
    "trend": "falling"
  },
  "ES": {
    "latestTime": "2025-Q4",
    "previousTime": "2025-Q3",
    "startValue": 1709349000000,
    "endValue": 1698225000000,
    "startDateISO": null,
    "endDateISO": null,
    "perSecond": -11124000000,
    "trend": "falling"
  },
  "FR": {
    "latestTime": "2025-Q4",
    "previousTime": "2025-Q3",
    "startValue": 3484061600000,
    "endValue": 3460465100000,
    "startDateISO": null,
    "endDateISO": null,
    "perSecond": -23596500000,
    "trend": "falling"
  },
  "HR": {
    "latestTime": "2025-Q4",
    "previousTime": "2025-Q3",
    "startValue": 51826500000,
    "endValue": 52370800000,
    "startDateISO": null,
    "endDateISO": null,
    "perSecond": 544300000,
    "trend": "rising"
  },
  "IT": {
    "latestTime": "2025-Q4",
    "previousTime": "2025-Q3",
    "startValue": 3081031600000,
    "endValue": 3095887600000,
    "startDateISO": null,
    "endDateISO": null,
    "perSecond": 14856000000,
    "trend": "rising"
  },
  "CY": {
    "latestTime": "2025-Q4",
    "previousTime": "2025-Q3",
    "startValue": 21695600000,
    "endValue": 20078200000,
    "startDateISO": null,
    "endDateISO": null,
    "perSecond": -1617400000,
    "trend": "falling"
  },
  "LV": {
    "latestTime": "2025-Q4",
    "previousTime": "2025-Q3",
    "startValue": 18965000000,
    "endValue": 20173900000,
    "startDateISO": null,
    "endDateISO": null,
    "perSecond": 1208900000,
    "trend": "rising"
  },
  "LT": {
    "latestTime": "2025-Q4",
    "previousTime": "2025-Q3",
    "startValue": 33634800000.000004,
    "endValue": 33259000000,
    "startDateISO": null,
    "endDateISO": null,
    "perSecond": -375800000.0000038,
    "trend": "falling"
  },
  "LU": {
    "latestTime": "2025-Q4",
    "previousTime": "2025-Q3",
    "startValue": 24292800000,
    "endValue": 23695100000,
    "startDateISO": null,
    "endDateISO": null,
    "perSecond": -597700000,
    "trend": "falling"
  },
  "HU": {
    "latestTime": "2025-Q4",
    "previousTime": "2025-Q3",
    "startValue": 164343900000,
    "endValue": 168536000000,
    "startDateISO": null,
    "endDateISO": null,
    "perSecond": 4192100000,
    "trend": "rising"
  },
  "MT": {
    "latestTime": "2025-Q4",
    "previousTime": "2025-Q3",
    "startValue": 11188700000,
    "endValue": 11397100000,
    "startDateISO": null,
    "endDateISO": null,
    "perSecond": 208400000,
    "trend": "rising"
  },
  "NL": {
    "latestTime": "2025-Q4",
    "previousTime": "2025-Q3",
    "startValue": 493301000000,
    "endValue": 523541000000,
    "startDateISO": null,
    "endDateISO": null,
    "perSecond": 30240000000,
    "trend": "rising"
  },
  "AT": {
    "latestTime": "2025-Q4",
    "previousTime": "2025-Q3",
    "startValue": 424012300000,
    "endValue": 418078500000,
    "startDateISO": null,
    "endDateISO": null,
    "perSecond": -5933800000,
    "trend": "falling"
  },
  "PL": {
    "latestTime": "2025-Q4",
    "previousTime": "2025-Q3",
    "startValue": 520348200000,
    "endValue": 553222700000,
    "startDateISO": null,
    "endDateISO": null,
    "perSecond": 32874500000,
    "trend": "rising"
  },
  "PT": {
    "latestTime": "2025-Q4",
    "previousTime": "2025-Q3",
    "startValue": 294507600000,
    "endValue": 275062800000,
    "startDateISO": null,
    "endDateISO": null,
    "perSecond": -19444800000,
    "trend": "falling"
  },
  "RO": {
    "latestTime": "2025-Q4",
    "previousTime": "2025-Q3",
    "startValue": 215780500000,
    "endValue": 223144700000,
    "startDateISO": null,
    "endDateISO": null,
    "perSecond": 7364200000,
    "trend": "rising"
  },
  "SI": {
    "latestTime": "2025-Q4",
    "previousTime": "2025-Q3",
    "startValue": 47046800000,
    "endValue": 46323600000,
    "startDateISO": null,
    "endDateISO": null,
    "perSecond": -723200000,
    "trend": "falling"
  },
  "SK": {
    "latestTime": "2025-Q4",
    "previousTime": "2025-Q3",
    "startValue": 83949300000,
    "endValue": 83956800000,
    "startDateISO": null,
    "endDateISO": null,
    "perSecond": 7500000,
    "trend": "rising"
  },
  "FI": {
    "latestTime": "2025-Q4",
    "previousTime": "2025-Q3",
    "startValue": 242412000000,
    "endValue": 248433000000,
    "startDateISO": null,
    "endDateISO": null,
    "perSecond": 6021000000,
    "trend": "rising"
  },
  "SE": {
    "latestTime": "2025-Q4",
    "previousTime": "2025-Q3",
    "startValue": 195860200000,
    "endValue": 213039000000,
    "startDateISO": null,
    "endDateISO": null,
    "perSecond": 17178800000,
    "trend": "rising"
  }
};
