// Auto-generated by scripts/fetch-eurostat.js
export const EUROSTAT_UPDATED_AT = "2026-04-24T23:39:25.583Z";
export const EUROSTAT_SERIES = {
  "BE": {
    "latestTime": "2025-Q4",
    "previousTime": "2025-Q3",
    "startValue": 680800000000,
    "endValue": 692461000000,
    "startDateISO": "2025-09-30T23:59:59.000Z",
    "endDateISO": "2025-12-31T23:59:59.000Z",
    "perSecond": 1467.013888888889,
    "trend": "rising"
  },
  "BG": {
    "latestTime": "2025-Q4",
    "previousTime": "2025-Q3",
    "startValue": 31824900000,
    "endValue": 34634900000,
    "startDateISO": "2025-09-30T23:59:59.000Z",
    "endDateISO": "2025-12-31T23:59:59.000Z",
    "perSecond": 353.5124798711755,
    "trend": "rising"
  },
  "CZ": {
    "latestTime": "2025-Q4",
    "previousTime": "2025-Q3",
    "startValue": 148896300000,
    "endValue": 156217800000,
    "startDateISO": "2025-09-30T23:59:59.000Z",
    "endDateISO": "2025-12-31T23:59:59.000Z",
    "perSecond": 921.0824275362319,
    "trend": "rising"
  },
  "DK": {
    "latestTime": "2025-Q4",
    "previousTime": "2025-Q3",
    "startValue": 120734800000,
    "endValue": 114501500000,
    "startDateISO": "2025-09-30T23:59:59.000Z",
    "endDateISO": "2025-12-31T23:59:59.000Z",
    "perSecond": -784.1812600644122,
    "trend": "falling"
  },
  "DE": {
    "latestTime": "2025-Q4",
    "previousTime": "2025-Q3",
    "startValue": 2789527600000,
    "endValue": 2838238900000,
    "startDateISO": "2025-09-30T23:59:59.000Z",
    "endDateISO": "2025-12-31T23:59:59.000Z",
    "perSecond": 6128.132548309179,
    "trend": "rising"
  },
  "EE": {
    "latestTime": "2025-Q4",
    "previousTime": "2025-Q3",
    "startValue": 9414200000,
    "endValue": 10035200000,
    "startDateISO": "2025-09-30T23:59:59.000Z",
    "endDateISO": "2025-12-31T23:59:59.000Z",
    "perSecond": 78.125,
    "trend": "rising"
  },
  "IE": {
    "latestTime": "2025-Q4",
    "previousTime": "2025-Q3",
    "startValue": 208911500000,
    "endValue": 209902300000,
    "startDateISO": "2025-09-30T23:59:59.000Z",
    "endDateISO": "2025-12-31T23:59:59.000Z",
    "perSecond": 124.64774557165862,
    "trend": "rising"
  },
  "GR": {
    "latestTime": "2025-Q4",
    "previousTime": "2025-Q3",
    "startValue": 367847000000,
    "endValue": 362925000000,
    "startDateISO": "2025-09-30T23:59:59.000Z",
    "endDateISO": "2025-12-31T23:59:59.000Z",
    "perSecond": -619.2129629629629,
    "trend": "falling"
  },
  "ES": {
    "latestTime": "2025-Q4",
    "previousTime": "2025-Q3",
    "startValue": 1709349000000,
    "endValue": 1698225000000,
    "startDateISO": "2025-09-30T23:59:59.000Z",
    "endDateISO": "2025-12-31T23:59:59.000Z",
    "perSecond": -1399.4565217391305,
    "trend": "falling"
  },
  "FR": {
    "latestTime": "2025-Q4",
    "previousTime": "2025-Q3",
    "startValue": 3484061600000,
    "endValue": 3460465100000,
    "startDateISO": "2025-09-30T23:59:59.000Z",
    "endDateISO": "2025-12-31T23:59:59.000Z",
    "perSecond": -2968.5612922705313,
    "trend": "falling"
  },
  "HR": {
    "latestTime": "2025-Q4",
    "previousTime": "2025-Q3",
    "startValue": 51826500000,
    "endValue": 52370800000,
    "startDateISO": "2025-09-30T23:59:59.000Z",
    "endDateISO": "2025-12-31T23:59:59.000Z",
    "perSecond": 68.47574476650564,
    "trend": "rising"
  },
  "IT": {
    "latestTime": "2025-Q4",
    "previousTime": "2025-Q3",
    "startValue": 3081031600000,
    "endValue": 3095887600000,
    "startDateISO": "2025-09-30T23:59:59.000Z",
    "endDateISO": "2025-12-31T23:59:59.000Z",
    "perSecond": 1868.961352657005,
    "trend": "rising"
  },
  "CY": {
    "latestTime": "2025-Q4",
    "previousTime": "2025-Q3",
    "startValue": 21695600000,
    "endValue": 20078200000,
    "startDateISO": "2025-09-30T23:59:59.000Z",
    "endDateISO": "2025-12-31T23:59:59.000Z",
    "perSecond": -203.47725442834138,
    "trend": "falling"
  },
  "LV": {
    "latestTime": "2025-Q4",
    "previousTime": "2025-Q3",
    "startValue": 18965000000,
    "endValue": 20173900000,
    "startDateISO": "2025-09-30T23:59:59.000Z",
    "endDateISO": "2025-12-31T23:59:59.000Z",
    "perSecond": 152.08584943639292,
    "trend": "rising"
  },
  "LT": {
    "latestTime": "2025-Q4",
    "previousTime": "2025-Q3",
    "startValue": 33634800000.000004,
    "endValue": 33259000000,
    "startDateISO": "2025-09-30T23:59:59.000Z",
    "endDateISO": "2025-12-31T23:59:59.000Z",
    "perSecond": -47.277576489533494,
    "trend": "falling"
  },
  "LU": {
    "latestTime": "2025-Q4",
    "previousTime": "2025-Q3",
    "startValue": 24292800000,
    "endValue": 23695100000,
    "startDateISO": "2025-09-30T23:59:59.000Z",
    "endDateISO": "2025-12-31T23:59:59.000Z",
    "perSecond": -75.19373993558776,
    "trend": "falling"
  },
  "HU": {
    "latestTime": "2025-Q4",
    "previousTime": "2025-Q3",
    "startValue": 164343900000,
    "endValue": 168536000000,
    "startDateISO": "2025-09-30T23:59:59.000Z",
    "endDateISO": "2025-12-31T23:59:59.000Z",
    "perSecond": 527.3877818035427,
    "trend": "rising"
  },
  "MT": {
    "latestTime": "2025-Q4",
    "previousTime": "2025-Q3",
    "startValue": 11188700000,
    "endValue": 11397100000,
    "startDateISO": "2025-09-30T23:59:59.000Z",
    "endDateISO": "2025-12-31T23:59:59.000Z",
    "perSecond": 26.21779388083736,
    "trend": "rising"
  },
  "NL": {
    "latestTime": "2025-Q4",
    "previousTime": "2025-Q3",
    "startValue": 493301000000,
    "endValue": 523541000000,
    "startDateISO": "2025-09-30T23:59:59.000Z",
    "endDateISO": "2025-12-31T23:59:59.000Z",
    "perSecond": 3804.3478260869565,
    "trend": "rising"
  },
  "AT": {
    "latestTime": "2025-Q4",
    "previousTime": "2025-Q3",
    "startValue": 424012300000,
    "endValue": 418078500000,
    "startDateISO": "2025-09-30T23:59:59.000Z",
    "endDateISO": "2025-12-31T23:59:59.000Z",
    "perSecond": -746.502616747182,
    "trend": "falling"
  },
  "PL": {
    "latestTime": "2025-Q4",
    "previousTime": "2025-Q3",
    "startValue": 520348200000,
    "endValue": 553222700000,
    "startDateISO": "2025-09-30T23:59:59.000Z",
    "endDateISO": "2025-12-31T23:59:59.000Z",
    "perSecond": 4135.781501610306,
    "trend": "rising"
  },
  "PT": {
    "latestTime": "2025-Q4",
    "previousTime": "2025-Q3",
    "startValue": 294507600000,
    "endValue": 275062800000,
    "startDateISO": "2025-09-30T23:59:59.000Z",
    "endDateISO": "2025-12-31T23:59:59.000Z",
    "perSecond": -2446.256038647343,
    "trend": "falling"
  },
  "RO": {
    "latestTime": "2025-Q4",
    "previousTime": "2025-Q3",
    "startValue": 215780500000,
    "endValue": 223144700000,
    "startDateISO": "2025-09-30T23:59:59.000Z",
    "endDateISO": "2025-12-31T23:59:59.000Z",
    "perSecond": 926.454307568438,
    "trend": "rising"
  },
  "SI": {
    "latestTime": "2025-Q4",
    "previousTime": "2025-Q3",
    "startValue": 47046800000,
    "endValue": 46323600000,
    "startDateISO": "2025-09-30T23:59:59.000Z",
    "endDateISO": "2025-12-31T23:59:59.000Z",
    "perSecond": -90.98228663446055,
    "trend": "falling"
  },
  "SK": {
    "latestTime": "2025-Q4",
    "previousTime": "2025-Q3",
    "startValue": 83949300000,
    "endValue": 83956800000,
    "startDateISO": "2025-09-30T23:59:59.000Z",
    "endDateISO": "2025-12-31T23:59:59.000Z",
    "perSecond": 0.9435386473429952,
    "trend": "rising"
  },
  "FI": {
    "latestTime": "2025-Q4",
    "previousTime": "2025-Q3",
    "startValue": 242412000000,
    "endValue": 248433000000,
    "startDateISO": "2025-09-30T23:59:59.000Z",
    "endDateISO": "2025-12-31T23:59:59.000Z",
    "perSecond": 757.4728260869565,
    "trend": "rising"
  },
  "SE": {
    "latestTime": "2025-Q4",
    "previousTime": "2025-Q3",
    "startValue": 195860200000,
    "endValue": 213039000000,
    "startDateISO": "2025-09-30T23:59:59.000Z",
    "endDateISO": "2025-12-31T23:59:59.000Z",
    "perSecond": 2161.1815619967792,
    "trend": "rising"
  }
};
