// Auto-generated by scripts/update-eurostat-ratios.js
export const EUROSTAT_RATIO_SNAPSHOT_ID = "2026-07-31T16:55:06.132Z|2026-Q1|PC_GDP";
export const EUROSTAT_RATIO_UPDATED_AT = "2026-07-31T16:55:06.132Z";
export const EUROSTAT_RATIO_UPDATE_REPORT = {
  "fetchedAt": "2026-07-31T16:55:06.132Z",
  "sourceLatestAvailableQuarter": "2026-Q1",
  "sourceUnit": "PC_GDP",
  "periodCounts": {
    "2026-Q1": 27
  },
  "dominantLatestTime": "2026-Q1",
  "dominantCoverage": 27,
  "latestAvailableTime": "2026-Q1",
  "acceptedCodes": [
    "AT",
    "BE",
    "BG",
    "HR",
    "CY",
    "CZ",
    "DK",
    "EE",
    "FI",
    "FR",
    "DE",
    "GR",
    "HU",
    "IE",
    "IT",
    "LV",
    "LT",
    "LU",
    "MT",
    "NL",
    "PL",
    "PT",
    "RO",
    "SK",
    "SI",
    "ES",
    "SE"
  ],
  "carriedForwardCodes": [],
  "regressedSourceCodes": [],
  "missingCodes": [],
  "staleCodes": [],
  "sourceMissingGeoKeys": [],
  "sourceUnknownGeoKeys": []
};
export const EUROSTAT_RATIO_SERIES = {
  "AT": {
    "latestTime": "2026-Q1",
    "ratioPct": 83.3
  },
  "BE": {
    "latestTime": "2026-Q1",
    "ratioPct": 109.1
  },
  "BG": {
    "latestTime": "2026-Q1",
    "ratioPct": 28.5
  },
  "HR": {
    "latestTime": "2026-Q1",
    "ratioPct": 58.4
  },
  "CY": {
    "latestTime": "2026-Q1",
    "ratioPct": 54.6
  },
  "CZ": {
    "latestTime": "2026-Q1",
    "ratioPct": 44.1
  },
  "DK": {
    "latestTime": "2026-Q1",
    "ratioPct": 26.8
  },
  "EE": {
    "latestTime": "2026-Q1",
    "ratioPct": 25.2
  },
  "FI": {
    "latestTime": "2026-Q1",
    "ratioPct": 89.7
  },
  "FR": {
    "latestTime": "2026-Q1",
    "ratioPct": 117.6
  },
  "DE": {
    "latestTime": "2026-Q1",
    "ratioPct": 64.4
  },
  "GR": {
    "latestTime": "2026-Q1",
    "ratioPct": 143.5
  },
  "HU": {
    "latestTime": "2026-Q1",
    "ratioPct": 77.7
  },
  "IE": {
    "latestTime": "2026-Q1",
    "ratioPct": 37
  },
  "IT": {
    "latestTime": "2026-Q1",
    "ratioPct": 138.9
  },
  "LV": {
    "latestTime": "2026-Q1",
    "ratioPct": 46.9
  },
  "LT": {
    "latestTime": "2026-Q1",
    "ratioPct": 42.3
  },
  "LU": {
    "latestTime": "2026-Q1",
    "ratioPct": 29.2
  },
  "MT": {
    "latestTime": "2026-Q1",
    "ratioPct": 45.9
  },
  "NL": {
    "latestTime": "2026-Q1",
    "ratioPct": 43.8
  },
  "PL": {
    "latestTime": "2026-Q1",
    "ratioPct": 61.6
  },
  "PT": {
    "latestTime": "2026-Q1",
    "ratioPct": 91
  },
  "RO": {
    "latestTime": "2026-Q1",
    "ratioPct": 60.1
  },
  "SK": {
    "latestTime": "2026-Q1",
    "ratioPct": 62.5
  },
  "SI": {
    "latestTime": "2026-Q1",
    "ratioPct": 64.8
  },
  "ES": {
    "latestTime": "2026-Q1",
    "ratioPct": 101.6
  },
  "SE": {
    "latestTime": "2026-Q1",
    "ratioPct": 34.9
  }
};
