const COPY = {
  en: {
    year: "Year",
    share: "Share this comparison",
    copyLink: "Copy link",
    copied: "Link copied",
    manualCopy: "Select and copy the link below.",
    shareUrl: "Link to this comparison",
    viewTrend: "View trend",
    details: "Details",
    chartSelect: "Inspect a month",
    chartHint: "Tap or click the chart, or use the month slider to inspect exact values.",
    freshness: "We compare the latest complete month across all countries. More recent flash estimates are excluded.",
    countryLink: "View inflation in {country}",
    countryLinkNote: "Compare consumer price changes with the euro area.",
    locale: "en-GB", shortTitle: "Inflation", eyebrow: "European economy · Prices",
    title: "Inflation in Europe", description: "Compare euro area inflation and inflation in all 27 EU countries. Explore monthly Eurostat HICP figures, an interactive map and historical charts.",
    intro: "How fast are prices rising? Compare inflation across Europe and see how your country moves alongside the euro area.",
    euroArea: "Euro area", eu: "European Union", annual: "Annual inflation", monthly: "Monthly change", countries: "Countries",
    latest: "Latest complete comparison", official: "Official Eurostat HICP data", explore: "Explore the map", methodologyLink: "Sources & methodology",
    comparison: "One month. A European comparison.", comparisonIntro: "Choose a month and a country. The map shows annual inflation: the change in prices compared with the same month a year earlier.",
    area: "Compare countries in", month: "Reference month", country: "Country", select: "Select a country", map: "Map of annual inflation by country",
    sameMonth: "All countries refer to the same month.", memberNote: "Euro area membership follows the selected month.",
    yearAgo: "Compared with the same month a year earlier", monthAgo: "Compared with the previous month", difference: "Difference from euro area", pp: "pp", ppLong: "percentage points",
    history: "Inflation through time", historyIntro: "Compare annual inflation in the selected country with the official euro area series.",
    horizon: "Chart period", years: "years", oneYear: "1 year", historyTable: "View the chart data", chartNote: "Gaps and breaks in a series are not connected. Monthly observations of annual inflation; no interpolation.",
    ranking: "Inflation by country", rankingIntro: "Compare annual inflation and monthly price changes. Select a country to update the map and chart.",
    sort: "Sort countries", descending: "Highest inflation first", ascending: "Lowest inflation first", alphabetical: "Country name", rank: "Rank", viewCountry: "Compare", noData: "No data", missing: "— = no observation. Missing values are never replaced by zero.",
    bands: ["Below 0%", "0 to <2%", "2 to <4%", "4 to <6%", "6% or more"],
    reading: "Understanding the numbers", explanations: [
      ["Annual is not monthly", "Annual inflation compares a month with the same month a year earlier. The monthly change compares it with the previous month. These are two different comparisons, not rates to add together."],
      ["Lower inflation does not mean lower prices", "If inflation falls from 4% to 2%, prices are still rising, just more slowly. A negative rate means the average price level fell over that comparison period."],
      ["A common measure, different experiences", "HICP is the harmonised index used to compare consumer price changes across countries. National CPI figures can differ. Your own spending pattern can also produce a different experience of inflation."],
    ],
    methodology: "Sources & methodology", source: "Source", dataset: "Eurostat monthly HICP dataset", definitions: "HICP definitions and coverage", releaseCalendar: "Publication and revision policy", membership: "Euro area membership (ECB)",
    fetched: "Data retrieved", updated: "Source updated", reviewed: "Methodology reviewed", coverage: "History available", sourceDetail: "Total HICP basket, ECOICOP version 2. Annual and monthly percentage changes are taken directly from Eurostat. Monthly changes are not seasonally adjusted.",
    releaseNote: "We use the latest month with both rates available for all 27 EU countries and the two official aggregates, without estimated, provisional or forecast flags. Newer flash estimates are excluded. A country awaiting complete data can delay this comparison. Published figures may be revised.",
    aggregateNote: "The euro area line uses Eurostat’s changing-composition aggregate (EA). The EU figure uses the fixed EU27 composition from 2020. These are official weighted aggregates, not a simple average of the country rates. The euro area filter includes Croatia from January 2023 and Bulgaria from January 2026.",
    historyNote: "The history uses the current dataset, including Eurostat revisions, from January 2015. Historical estimates and provisional observations retain their flags; forecasts are not displayed. Since 2026, HICP uses ECOICOP version 2 and the index reference year 2025=100; this page displays rates, not index levels.",
    flagsTitle: "Observation flags", flags: { b: "break in series", d: "definition differs", e: "estimated", p: "provisional", f: "forecast (excluded)", u: "low reliability", r: "revised" },
    debtLink: "Explore government debt", debtText: "Continue exploring Europe’s public finances with the EU debt map.",
  },
  nl: {
    year: "Jaar",
    share: "Deel deze vergelijking",
    copyLink: "Link kopiëren",
    copied: "Link gekopieerd",
    manualCopy: "Selecteer en kopieer de link hieronder.",
    shareUrl: "Link naar deze vergelijking",
    viewTrend: "Bekijk ontwikkeling",
    details: "Details",
    chartSelect: "Bekijk een maand",
    chartHint: "Tik of klik op de grafiek, of gebruik de maandschuif om de exacte cijfers te bekijken.",
    freshness: "We vergelijken de laatste volledige maand voor alle landen. Recentere snelle ramingen zijn uitgesloten.",
    countryLink: "Bekijk de inflatie in {country}",
    countryLinkNote: "Vergelijk de consumentenprijsontwikkeling met de eurozone.",
    locale: "nl-NL", shortTitle: "Inflatie", eyebrow: "Europese economie · Prijzen",
    title: "Inflatie in Europa", description: "Vergelijk de inflatie in de eurozone en alle 27 EU-landen. Bekijk maandelijkse HICP-cijfers van Eurostat, een interactieve kaart en historische grafieken.",
    intro: "Hoe snel stijgen de prijzen? Vergelijk de inflatie in Europa en bekijk hoe jouw land zich verhoudt tot de eurozone.",
    euroArea: "Eurozone", eu: "Europese Unie", annual: "Jaarinflatie", monthly: "Maandmutatie", countries: "Landen",
    latest: "Laatste volledige vergelijking", official: "Officiële HICP-cijfers van Eurostat", explore: "Bekijk de kaart", methodologyLink: "Bronnen & methode",
    comparison: "Eén maand. Een Europese vergelijking.", comparisonIntro: "Kies een maand en een land. De kaart toont de jaarinflatie: de prijsverandering ten opzichte van dezelfde maand een jaar eerder.",
    area: "Vergelijk landen in", month: "Referentiemaand", country: "Land", select: "Kies een land", map: "Kaart van de jaarinflatie per land",
    sameMonth: "Alle landen hebben dezelfde referentiemaand.", memberNote: "Het lidmaatschap van de eurozone volgt de gekozen maand.",
    yearAgo: "Ten opzichte van dezelfde maand een jaar eerder", monthAgo: "Ten opzichte van de vorige maand", difference: "Verschil met de eurozone", pp: "pp", ppLong: "procentpunt",
    history: "Inflatie door de tijd", historyIntro: "Vergelijk de jaarinflatie in het gekozen land met de officiële reeks voor de eurozone.",
    horizon: "Grafiekperiode", years: "jaar", oneYear: "1 jaar", historyTable: "Bekijk de grafiekgegevens", chartNote: "Ontbrekende waarden en reeksbreuken worden niet met lijnen overbrugd. Maandelijkse waarnemingen van de jaarinflatie; geen interpolatie.",
    ranking: "Inflatie per land", rankingIntro: "Vergelijk de jaarinflatie en de maandelijkse prijsverandering. Selecteer een land om de kaart en grafiek bij te werken.",
    sort: "Landen sorteren", descending: "Hoogste inflatie eerst", ascending: "Laagste inflatie eerst", alphabetical: "Landnaam", rank: "Rang", viewCountry: "Vergelijk", noData: "Geen gegevens", missing: "— = geen waarneming. Ontbrekende waarden worden nooit vervangen door nul.",
    bands: ["Onder 0%", "0 tot <2%", "2 tot <4%", "4 tot <6%", "6% of hoger"],
    reading: "De cijfers begrijpen", explanations: [
      ["Jaarinflatie is geen maandmutatie", "De jaarinflatie vergelijkt een maand met dezelfde maand een jaar eerder. De maandmutatie vergelijkt met de vorige maand. Dit zijn twee verschillende vergelijkingen; je telt deze percentages niet bij elkaar op."],
      ["Lagere inflatie betekent geen lagere prijzen", "Daalt de inflatie van 4% naar 2%, dan stijgen prijzen nog steeds, maar langzamer. Een negatief percentage betekent dat het gemiddelde prijsniveau in die vergelijkingsperiode daalde."],
      ["Eén maatstaf, verschillende ervaringen", "De HICP is de geharmoniseerde index voor het vergelijken van consumentenprijsveranderingen tussen landen. Nationale CPI-cijfers kunnen afwijken. Ook jouw eigen uitgavenpatroon kan een andere inflatiebeleving opleveren."],
    ],
    methodology: "Bronnen & methode", source: "Bron", dataset: "Maandelijkse HICP-dataset van Eurostat", definitions: "HICP-definities en dekking", releaseCalendar: "Publicatie- en herzieningsbeleid", membership: "Lidmaatschap van de eurozone (ECB)",
    fetched: "Gegevens opgehaald", updated: "Bron bijgewerkt", reviewed: "Methode gecontroleerd", coverage: "Beschikbare historie", sourceDetail: "Totale HICP-bestedingskorf, ECOICOP versie 2. De jaarlijkse en maandelijkse procentuele veranderingen komen rechtstreeks van Eurostat. Maandmutaties zijn niet seizoengecorrigeerd.",
    releaseNote: "We gebruiken de laatste maand waarin beide percentages beschikbaar zijn voor alle 27 EU-landen en de twee officiële aggregaten, zonder markering als raming, voorlopig cijfer of prognose. Nieuwere snelle ramingen zijn uitgesloten. Als een land nog geen volledige gegevens heeft, kan deze vergelijking achterlopen. Gepubliceerde cijfers kunnen worden herzien.",
    aggregateNote: "De eurozonelijn gebruikt het Eurostat-aggregaat met veranderende samenstelling (EA). Het EU-cijfer gebruikt de vaste EU27-samenstelling vanaf 2020. Dit zijn officiële gewogen aggregaten, geen eenvoudig gemiddelde van de landenpercentages. Het eurozonefilter bevat Kroatië vanaf januari 2023 en Bulgarije vanaf januari 2026.",
    historyNote: "De historie gebruikt de huidige dataset, inclusief herzieningen door Eurostat, vanaf januari 2015. Historische ramingen en voorlopige cijfers behouden hun markering; prognoses worden niet getoond. Sinds 2026 gebruikt de HICP ECOICOP versie 2 en het indexbasisjaar 2025=100; deze pagina toont mutaties, geen indexstanden.",
    flagsTitle: "Markeringen bij waarnemingen", flags: { b: "reeksbreuk", d: "afwijkende definitie", e: "raming", p: "voorlopig", f: "prognose (uitgesloten)", u: "lage betrouwbaarheid", r: "herzien" },
    debtLink: "Bekijk de overheidsschuld", debtText: "Ontdek ook de Europese overheidsfinanciën op de EU-schuldkaart.",
  },
  de: {
    year: "Jahr",
    share: "Diesen Vergleich teilen",
    copyLink: "Link kopieren",
    copied: "Link kopiert",
    manualCopy: "Wählen und kopieren Sie den Link unten.",
    shareUrl: "Link zu diesem Vergleich",
    viewTrend: "Entwicklung ansehen",
    details: "Details",
    chartSelect: "Monat ansehen",
    chartHint: "Tippen oder klicken Sie auf das Diagramm oder nutzen Sie den Monatsregler, um genaue Werte anzuzeigen.",
    freshness: "Wir vergleichen den neuesten vollständigen Monat für alle Länder. Neuere Schnellschätzungen sind ausgeschlossen.",
    countryLink: "Inflation in {country} ansehen",
    countryLinkNote: "Verbraucherpreisänderungen mit dem Euroraum vergleichen.",
    locale: "de-DE", shortTitle: "Inflation", eyebrow: "Europäische Wirtschaft · Preise",
    title: "Inflation in Europa", description: "Vergleichen Sie die Inflation im Euroraum und in allen 27 EU-Ländern: monatliche HVPI-Daten von Eurostat, interaktive Karte und historische Diagramme.",
    intro: "Wie schnell steigen die Preise? Vergleichen Sie die Inflation in Europa und die Entwicklung Ihres Landes mit dem Euroraum.",
    euroArea: "Euroraum", eu: "Europäische Union", annual: "Jährliche Inflationsrate", monthly: "Monatliche Veränderung", countries: "Länder",
    latest: "Neuester vollständiger Vergleich", official: "Offizielle HVPI-Daten von Eurostat", explore: "Zur Karte", methodologyLink: "Quellen & Methodik",
    comparison: "Ein Monat. Ein europäischer Vergleich.", comparisonIntro: "Wählen Sie einen Monat und ein Land. Die Karte zeigt die jährliche Inflationsrate: die Preisveränderung gegenüber demselben Monat des Vorjahres.",
    area: "Länder vergleichen im", month: "Bezugsmonat", country: "Land", select: "Land auswählen", map: "Karte der jährlichen Inflation nach Land",
    sameMonth: "Alle Länder beziehen sich auf denselben Monat.", memberNote: "Die Mitgliedschaft im Euroraum richtet sich nach dem gewählten Monat.",
    yearAgo: "Gegenüber demselben Monat des Vorjahres", monthAgo: "Gegenüber dem Vormonat", difference: "Abstand zum Euroraum", pp: "Pp.", ppLong: "Prozentpunkte",
    history: "Inflation im Zeitverlauf", historyIntro: "Vergleichen Sie die jährliche Inflation im gewählten Land mit der offiziellen Zeitreihe des Euroraums.",
    horizon: "Diagrammzeitraum", years: "Jahre", oneYear: "1 Jahr", historyTable: "Diagrammdaten anzeigen", chartNote: "Fehlende Werte und Zeitreihenbrüche werden nicht durch Linien überbrückt. Monatliche Beobachtungen der jährlichen Inflation; keine Interpolation.",
    ranking: "Inflation nach Land", rankingIntro: "Vergleichen Sie jährliche Inflationsraten und monatliche Preisveränderungen. Wählen Sie ein Land, um Karte und Diagramm zu aktualisieren.",
    sort: "Länder sortieren", descending: "Höchste Inflation zuerst", ascending: "Niedrigste Inflation zuerst", alphabetical: "Ländername", rank: "Rang", viewCountry: "Vergleichen", noData: "Keine Daten", missing: "— = keine Beobachtung. Fehlende Werte werden niemals durch null ersetzt.",
    bands: ["Unter 0%", "0 bis <2%", "2 bis <4%", "4 bis <6%", "Ab 6%"],
    reading: "Die Zahlen verstehen", explanations: [
      ["Jährlich ist nicht monatlich", "Die jährliche Inflationsrate vergleicht einen Monat mit demselben Monat des Vorjahres. Die monatliche Veränderung vergleicht ihn mit dem Vormonat. Es handelt sich um zwei verschiedene Vergleiche, deren Raten nicht addiert werden."],
      ["Weniger Inflation bedeutet nicht niedrigere Preise", "Sinkt die Inflation von 4% auf 2%, steigen die Preise weiter, nur langsamer. Eine negative Rate bedeutet, dass das durchschnittliche Preisniveau im jeweiligen Vergleichszeitraum gesunken ist."],
      ["Ein Maßstab, unterschiedliche Erfahrungen", "Der HVPI ist der harmonisierte Index zum Vergleich der Verbraucherpreisveränderungen zwischen Ländern. Nationale Verbraucherpreisindizes können abweichen. Auch Ihr persönliches Ausgabenmuster kann zu einer anderen Inflationserfahrung führen."],
    ],
    methodology: "Quellen & Methodik", source: "Quelle", dataset: "Monatlicher HVPI-Datensatz von Eurostat", definitions: "HVPI-Definitionen und Abdeckung", releaseCalendar: "Veröffentlichungs- und Revisionsregeln", membership: "Mitgliedschaft im Euroraum (EZB)",
    fetched: "Daten abgerufen", updated: "Quelle aktualisiert", reviewed: "Methodik geprüft", coverage: "Verfügbare Zeitreihe", sourceDetail: "Gesamter HVPI-Warenkorb, ECOICOP Version 2. Jährliche und monatliche prozentuale Veränderungen stammen direkt von Eurostat. Monatliche Veränderungen sind nicht saisonbereinigt.",
    releaseNote: "Verwendet wird der neueste Monat mit beiden Raten für alle 27 EU-Länder und die zwei offiziellen Aggregate, ohne Kennzeichnung als geschätzt, vorläufig oder prognostiziert. Neuere Schnellschätzungen sind ausgeschlossen. Ausstehende vollständige Daten eines Landes können den Vergleich verzögern. Veröffentlichte Zahlen können revidiert werden.",
    aggregateNote: "Die Euroraum-Linie verwendet das Eurostat-Aggregat mit wechselnder Zusammensetzung (EA). Der EU-Wert verwendet die feste EU27-Zusammensetzung ab 2020. Dies sind offizielle gewichtete Aggregate, keine einfachen Mittelwerte der Länderraten. Der Euroraum-Filter umfasst Kroatien ab Januar 2023 und Bulgarien ab Januar 2026.",
    historyNote: "Die Zeitreihe verwendet den aktuellen Datensatz einschließlich Eurostat-Revisionen ab Januar 2015. Historische Schätzungen und vorläufige Werte behalten ihre Kennzeichnung; Prognosen werden nicht angezeigt. Seit 2026 verwendet der HVPI ECOICOP Version 2 und das Indexbasisjahr 2025=100; diese Seite zeigt Veränderungsraten, keine Indexstände.",
    flagsTitle: "Kennzeichnungen der Beobachtungen", flags: { b: "Zeitreihenbruch", d: "abweichende Definition", e: "geschätzt", p: "vorläufig", f: "Prognose (ausgeschlossen)", u: "geringe Zuverlässigkeit", r: "revidiert" },
    debtLink: "Staatsschulden erkunden", debtText: "Entdecken Sie auch Europas öffentliche Finanzen auf der EU-Schuldenkarte.",
  },
  fr: {
    year: "Année",
    share: "Partager cette comparaison",
    copyLink: "Copier le lien",
    copied: "Lien copié",
    manualCopy: "Sélectionnez et copiez le lien ci-dessous.",
    shareUrl: "Lien vers cette comparaison",
    viewTrend: "Voir l’évolution",
    details: "Détails",
    chartSelect: "Examiner un mois",
    chartHint: "Touchez ou cliquez sur le graphique, ou utilisez le curseur mensuel pour afficher les valeurs exactes.",
    freshness: "Nous comparons le dernier mois complet pour tous les pays. Les estimations rapides plus récentes sont exclues.",
    countryLink: "Voir l’inflation : {country}",
    countryLinkNote: "Comparer l’évolution des prix à la consommation avec la zone euro.",
    locale: "fr-FR", shortTitle: "Inflation", eyebrow: "Économie européenne · Prix",
    title: "L’inflation en Europe", description: "Comparez l’inflation dans la zone euro et les 27 pays de l’UE : données mensuelles IPCH d’Eurostat, carte interactive et graphiques historiques.",
    intro: "À quelle vitesse les prix augmentent-ils ? Comparez l’inflation en Europe et l’évolution de votre pays avec celle de la zone euro.",
    euroArea: "Zone euro", eu: "Union européenne", annual: "Inflation annuelle", monthly: "Variation mensuelle", countries: "Pays",
    latest: "Dernière comparaison complète", official: "Données IPCH officielles d’Eurostat", explore: "Voir la carte", methodologyLink: "Sources et méthode",
    comparison: "Un mois. Une comparaison européenne.", comparisonIntro: "Choisissez un mois et un pays. La carte présente l’inflation annuelle : la variation des prix par rapport au même mois de l’année précédente.",
    area: "Comparer les pays de", month: "Mois de référence", country: "Pays", select: "Choisir un pays", map: "Carte de l’inflation annuelle par pays",
    sameMonth: "Tous les pays se rapportent au même mois.", memberNote: "L’appartenance à la zone euro correspond au mois sélectionné.",
    yearAgo: "Par rapport au même mois de l’année précédente", monthAgo: "Par rapport au mois précédent", difference: "Écart avec la zone euro", pp: "pt", ppLong: "points de pourcentage",
    history: "L’inflation au fil du temps", historyIntro: "Comparez l’inflation annuelle du pays choisi avec la série officielle de la zone euro.",
    horizon: "Période du graphique", years: "ans", oneYear: "1 an", historyTable: "Voir les données du graphique", chartNote: "Les valeurs manquantes et les ruptures de série ne sont pas reliées. Observations mensuelles de l’inflation annuelle ; aucune interpolation.",
    ranking: "Inflation par pays", rankingIntro: "Comparez l’inflation annuelle et les variations mensuelles des prix. Sélectionnez un pays pour actualiser la carte et le graphique.",
    sort: "Trier les pays", descending: "Inflation la plus élevée", ascending: "Inflation la plus faible", alphabetical: "Nom du pays", rank: "Rang", viewCountry: "Comparer", noData: "Pas de données", missing: "— = aucune observation. Les valeurs manquantes ne sont jamais remplacées par zéro.",
    bands: ["Moins de 0 %", "0 à <2 %", "2 à <4 %", "4 à <6 %", "6 % ou plus"],
    reading: "Comprendre les chiffres", explanations: [
      ["Annuel ne signifie pas mensuel", "L’inflation annuelle compare un mois au même mois de l’année précédente. La variation mensuelle le compare au mois précédent. Ce sont deux comparaisons différentes dont les taux ne s’additionnent pas."],
      ["Moins d’inflation ne signifie pas une baisse des prix", "Si l’inflation passe de 4 % à 2 %, les prix continuent d’augmenter, mais plus lentement. Un taux négatif signifie que le niveau moyen des prix a baissé sur la période de comparaison."],
      ["Une mesure commune, des expériences différentes", "L’IPCH est l’indice harmonisé qui permet de comparer les variations des prix à la consommation entre pays. Les indices nationaux peuvent différer. Vos propres dépenses peuvent également conduire à une perception différente de l’inflation."],
    ],
    methodology: "Sources et méthode", source: "Source", dataset: "Données mensuelles IPCH d’Eurostat", definitions: "Définitions et couverture de l’IPCH", releaseCalendar: "Politique de publication et de révision", membership: "Appartenance à la zone euro (BCE)",
    fetched: "Données récupérées", updated: "Source actualisée", reviewed: "Méthode vérifiée", coverage: "Historique disponible", sourceDetail: "Ensemble du panier IPCH, ECOICOP version 2. Les variations annuelles et mensuelles en pourcentage proviennent directement d’Eurostat. Les variations mensuelles ne sont pas corrigées des variations saisonnières.",
    releaseNote: "Nous retenons le dernier mois avec les deux taux pour les 27 pays de l’UE et les deux agrégats officiels, sans indicateur d’estimation, de donnée provisoire ou de prévision. Les estimations rapides plus récentes sont exclues. Des données complètes encore attendues pour un pays peuvent retarder la comparaison. Les chiffres publiés peuvent être révisés.",
    aggregateNote: "La courbe de la zone euro utilise l’agrégat Eurostat à composition évolutive (EA). Le chiffre de l’UE utilise la composition fixe UE27 depuis 2020. Ce sont des agrégats officiels pondérés, et non une simple moyenne des taux nationaux. Le filtre zone euro inclut la Croatie depuis janvier 2023 et la Bulgarie depuis janvier 2026.",
    historyNote: "L’historique utilise le jeu de données actuel, avec les révisions d’Eurostat, depuis janvier 2015. Les estimations et données provisoires historiques conservent leurs indicateurs ; les prévisions ne sont pas affichées. Depuis 2026, l’IPCH utilise ECOICOP version 2 et la base 2025=100 ; cette page présente des taux de variation, pas des niveaux d’indice.",
    flagsTitle: "Indicateurs des observations", flags: { b: "rupture de série", d: "définition différente", e: "estimation", p: "provisoire", f: "prévision (exclue)", u: "faible fiabilité", r: "révisé" },
    debtLink: "Explorer la dette publique", debtText: "Découvrez aussi les finances publiques européennes sur la carte de la dette de l’UE.",
  },
};
function getInflationCopy(lang = "en") { return COPY[lang] || COPY.en; }
function formatMonth(month, lang = "en", short = false) {
  return new Intl.DateTimeFormat(getInflationCopy(lang).locale, { month: short ? "short" : "long", year: "numeric", timeZone: "UTC" }).format(new Date(`${month}-01T00:00:00Z`));
}
function formatRate(value, lang = "en", signed = false) {
  if (!Number.isFinite(value)) return "—";
  return new Intl.NumberFormat(getInflationCopy(lang).locale, { style: "percent", minimumFractionDigits: 1, maximumFractionDigits: 1, signDisplay: signed ? "exceptZero" : "auto" }).format(value / 100);
}
function formatPoints(value, lang = "en") {
  if (!Number.isFinite(value)) return "—";
  return `${new Intl.NumberFormat(getInflationCopy(lang).locale, { minimumFractionDigits: 1, maximumFractionDigits: 1, signDisplay: "exceptZero" }).format(Math.round(value * 10) / 10)} ${getInflationCopy(lang).pp}`;
}
function statusText(status, lang, sourceLabels = {}) {
  return [...new Set(status.replace(/ /g, ""))].map(flag => getInflationCopy(lang).flags[flag] || sourceLabels[flag] || flag).join(", ");
}
module.exports = { COPY, getInflationCopy, formatMonth, formatRate, formatPoints, statusText };
